// Code generated by tools/database/gen_spelldata. DO NOT EDIT.

package warlock

import (
	"github.com/wowsims/forever/sim/core/spelldata"
)

// Generated with an effect held at its base points, the talent tree stating no rank value for it:
//   Decimation: effect 2 of spell 440870 has no rank curve and is held at its base points
//   Demonic Embrace: effect 1 of spell 18697 has no rank curve and is held at its base points
//   Demonic Pact: effect 0 of spell 425464 has no rank curve and is held at its base points
//   Pyroclasm: effect 1 of spell 18073 has no rank curve and is held at its base points

type generatedSpellData struct {
	Aftermath                   spelldata.Ladder
	AftermathTriggered          spelldata.Ladder
	AgonizingFlames             spelldata.Ladder
	AmplifyCurse                spelldata.Ladder
	Bane                        spelldata.Ladder
	BaneOfAgony                 spelldata.Ladder
	BaneOfDoom                  spelldata.Ladder
	BaneOfDoomEffect            spelldata.Ladder
	BaneOfHavoc                 spelldata.Ladder
	Banish                      spelldata.Ladder
	Cataclysm                   spelldata.Ladder
	Conflagrate                 spelldata.Ladder
	Corruption                  spelldata.Ladder
	CreateFirestone             spelldata.Ladder
	CreateFirestoneTriggered    spelldata.Ladder
	CreateHealthstone           spelldata.Ladder
	CreateHealthstoneTriggered  spelldata.Ladder
	CreateSoulstone             spelldata.Ladder
	CreateSoulstoneTriggered    spelldata.Ladder
	CreateSpellstone            spelldata.Ladder
	CreateSpellstoneTriggered   spelldata.Ladder
	CurseOfExhaustion           spelldata.Ladder
	CurseOfIdiocy               spelldata.Ladder
	CurseOfRecklessness         spelldata.Ladder
	CurseOfTongues              spelldata.Ladder
	CurseOfWeakness             spelldata.Ladder
	CurseOfTheElements          spelldata.Ladder
	DeathCoil                   spelldata.Ladder
	Decimation                  spelldata.Ladder
	DecimationTriggered         spelldata.Ladder
	DemonArmor                  spelldata.Ladder
	DemonSkin                   spelldata.Ladder
	DemonicAegis                spelldata.Ladder
	DemonicBrand                spelldata.Ladder
	DemonicBrandTriggered       spelldata.Ladder
	DemonicEmbrace              spelldata.Ladder
	DemonicEnergies             spelldata.Ladder
	DemonicKnowledge            spelldata.Ladder
	DemonicPact                 spelldata.Ladder
	DemonicSacrifice            spelldata.Ladder
	DemonicSacrificeTriggered   spelldata.Ladder
	DestructiveReach            spelldata.Ladder
	DetectInvisibility          spelldata.Ladder
	DrainLife                   spelldata.Ladder
	DrainMana                   spelldata.Ladder
	DrainSoul                   spelldata.Ladder
	ExplorerImp                 spelldata.Ladder
	Fear                        spelldata.Ladder
	FelConcentration            spelldata.Ladder
	FelDomination               spelldata.Ladder
	FelVitality                 spelldata.Ladder
	FireAndBrimstone            spelldata.Ladder
	HealthFunnel                spelldata.Ladder
	Hellfire                    spelldata.Ladder
	HellfireTriggered           spelldata.Ladder
	HellfireEffect              spelldata.Ladder
	HowlOfTerror                spelldata.Ladder
	Immolate                    spelldata.Ladder
	ImprovedBaneOfAgony         spelldata.Ladder
	ImprovedCorruption          spelldata.Ladder
	ImprovedCurseOfExhaustion   spelldata.Ladder
	ImprovedCurseOfWeakness     spelldata.Ladder
	ImprovedDrains              spelldata.Ladder
	ImprovedFelhunter           spelldata.Ladder
	ImprovedFirebolt            spelldata.Ladder
	ImprovedFirestone           spelldata.Ladder
	ImprovedHealthFunnel        spelldata.Ladder
	ImprovedHealthstone         spelldata.Ladder
	ImprovedImmolate            spelldata.Ladder
	ImprovedImp                 spelldata.Ladder
	ImprovedLashOfPain          spelldata.Ladder
	ImprovedLifeTap             spelldata.Ladder
	ImprovedSayaad              spelldata.Ladder
	ImprovedShadowBolt          spelldata.Ladder
	ImprovedShadowBoltTriggered spelldata.Ladder
	ImprovedSpellstone          spelldata.Ladder
	ImprovedSubjugateDemon      spelldata.Ladder
	ImprovedVoidwalker          spelldata.Ladder
	Incinerate                  spelldata.Ladder
	Intensity                   spelldata.Ladder
	LifeTap                     spelldata.Ladder
	LifeTapTriggered            spelldata.Ladder
	Malediction                 spelldata.Ladder
	Malevolence                 spelldata.Ladder
	MasterDemonologist          spelldata.Ladder
	MasterSummoner              spelldata.Ladder
	MetamorphosisDemonCharge    spelldata.Ladder
	MoltenSkin                  spelldata.Ladder
	Nightfall                   spelldata.Ladder
	NightfallTriggered          spelldata.Ladder
	Pandemic                    spelldata.Ladder
	PortalOfSummoning           spelldata.Ladder
	Pyroclasm                   spelldata.Ladder
	PyroclasmTriggered          spelldata.Ladder
	RainOfFire                  spelldata.Ladder
	RainOfFireTriggered         spelldata.Ladder
	RitualOfDoom                spelldata.Ladder
	RitualOfSummoning           spelldata.Ladder
	Ruin                        spelldata.Ladder
	SearingPain                 spelldata.Ladder
	SenseDemons                 spelldata.Ladder
	ShadowBolt                  spelldata.Ladder
	ShadowCleave                spelldata.Ladder
	ShadowCleaveTriggered       spelldata.Ladder
	ShadowMastery               spelldata.Ladder
	ShadowWard                  spelldata.Ladder
	ShadowAndFlame              spelldata.Ladder
	ShadowAndFlameTriggered     spelldata.Ladder
	Shadowburn                  spelldata.Ladder
	SiphonLife                  spelldata.Ladder
	SoulFire                    spelldata.Ladder
	SoulHarvest                 spelldata.Ladder
	SoulHarvestTriggered        spelldata.Ladder
	SoulLink                    spelldata.Ladder
	SoulLinkTriggered           spelldata.Ladder
	SoulSiphon                  spelldata.Ladder
	SubjugateDemon              spelldata.Ladder
	Suppression                 spelldata.Ladder
	UnendingBreath              spelldata.Ladder
	UnholyPower                 spelldata.Ladder
	Wrack                       spelldata.Ladder
}

var spellData = generatedSpellData{
	Aftermath:                   spelldata.Talent(18119, 5),
	AftermathTriggered:          spelldata.Ranked(18118),
	AgonizingFlames:             spelldata.Talent(17927, 3),
	AmplifyCurse:                spelldata.Ranked(18288),
	Bane:                        spelldata.Talent(17788, 5),
	BaneOfAgony:                 spelldata.Ranked(980, 1014, 6217, 11711, 11712, 11713),
	BaneOfDoom:                  spelldata.Ranked(603),
	BaneOfDoomEffect:            spelldata.Ranked(18662),
	BaneOfHavoc:                 spelldata.Ranked(1225228),
	Banish:                      spelldata.Ranked(710, 18647),
	Cataclysm:                   spelldata.Talent(17778, 3),
	Conflagrate:                 spelldata.Ranked(1293817, 1293818, 17962, 18930, 18931, 18932),
	Corruption:                  spelldata.Ranked(172, 6222, 6223, 7648, 11671, 11672, 25311),
	CreateFirestone:             spelldata.Ranked(6366, 17951, 17952, 17953),
	CreateFirestoneTriggered:    spelldata.Ranked(23480, 23481, 23482, 23483),
	CreateHealthstone:           spelldata.Ranked(6201, 6202, 5699, 11729, 11730),
	CreateHealthstoneTriggered:  spelldata.Ranked(6262, 6263, 5720, 5723, 11732),
	CreateSoulstone:             spelldata.Ranked(693, 20752, 20755, 20756, 20757),
	CreateSoulstoneTriggered:    spelldata.Ranked(3026, 20758, 20759, 20760, 20761),
	CreateSpellstone:            spelldata.Ranked(2362, 17727, 17728),
	CreateSpellstoneTriggered:   spelldata.Ranked(1237162, 1237164, 1237165),
	CurseOfExhaustion:           spelldata.Ranked(18223),
	CurseOfIdiocy:               spelldata.Ranked(1010),
	CurseOfRecklessness:         spelldata.Ranked(704, 7658, 7659, 11717),
	CurseOfTongues:              spelldata.Ranked(1714, 11719),
	CurseOfWeakness:             spelldata.Ranked(702, 1108, 6205, 7646, 11707, 11708),
	CurseOfTheElements:          spelldata.Ranked(440892, 1311676, 1311677, 1311680),
	DeathCoil:                   spelldata.Ranked(6789, 17925, 17926),
	Decimation:                  spelldata.Talent(440870, 2),
	DecimationTriggered:         spelldata.Ranked(440873),
	DemonArmor:                  spelldata.Ranked(706, 1086, 11733, 11734, 11735),
	DemonSkin:                   spelldata.Ranked(687, 696),
	DemonicAegis:                spelldata.Talent(1235316, 2),
	DemonicBrand:                spelldata.Talent(1293695, 3),
	DemonicBrandTriggered:       spelldata.Ranked(1293696),
	DemonicEmbrace:              spelldata.Talent(18697, 5),
	DemonicEnergies:             spelldata.Talent(1225214, 2),
	DemonicKnowledge:            spelldata.Talent(412732, 3),
	DemonicPact:                 spelldata.Talent(425464, 1),
	DemonicSacrifice:            spelldata.Ranked(18788),
	DemonicSacrificeTriggered:   spelldata.Ranked(18789, 18790, 18791, 18792),
	DestructiveReach:            spelldata.Talent(17917, 2),
	DetectInvisibility:          spelldata.Ranked(132, 2970, 11743),
	DrainLife:                   spelldata.Ranked(689, 699, 709, 7651, 11699, 11700),
	DrainMana:                   spelldata.Ranked(5138, 6226, 11703, 11704),
	DrainSoul:                   spelldata.Ranked(1120, 8288, 8289, 11675),
	ExplorerImp:                 spelldata.Ranked(445459),
	Fear:                        spelldata.Ranked(5782, 6213, 6215),
	FelConcentration:            spelldata.Talent(17783, 3),
	FelDomination:               spelldata.Ranked(18708),
	FelVitality:                 spelldata.Talent(18731, 3),
	FireAndBrimstone:            spelldata.Talent(412751, 3),
	HealthFunnel:                spelldata.Ranked(755, 3698, 3699, 3700, 11693, 11694, 11695),
	Hellfire:                    spelldata.Ranked(1949, 11683, 11684),
	HellfireTriggered:           spelldata.Ranked(5857, 11681, 11682),
	HellfireEffect:              spelldata.Ranked(5857, 11681, 11682),
	HowlOfTerror:                spelldata.Ranked(5484, 17928),
	Immolate:                    spelldata.Ranked(348, 707, 1094, 2941, 11665, 11667, 11668, 25309),
	ImprovedBaneOfAgony:         spelldata.Talent(18827, 2),
	ImprovedCorruption:          spelldata.Talent(17810, 5),
	ImprovedCurseOfExhaustion:   spelldata.Ranked(18310, 18311, 18312, 18313),
	ImprovedCurseOfWeakness:     spelldata.Ranked(18179, 18180, 18181),
	ImprovedDrains:              spelldata.Talent(403511, 3),
	ImprovedFelhunter:           spelldata.Talent(1225217, 3),
	ImprovedFirebolt:            spelldata.Ranked(18126, 18127),
	ImprovedFirestone:           spelldata.Ranked(18767, 18768),
	ImprovedHealthFunnel:        spelldata.Talent(18703, 2),
	ImprovedHealthstone:         spelldata.Ranked(18692, 18693),
	ImprovedImmolate:            spelldata.Ranked(17815, 17833, 17834, 17835, 17836),
	ImprovedImp:                 spelldata.Talent(18694, 3),
	ImprovedLashOfPain:          spelldata.Ranked(18128, 18129),
	ImprovedLifeTap:             spelldata.Talent(18182, 2),
	ImprovedSayaad:              spelldata.Talent(18754, 3),
	ImprovedShadowBolt:          spelldata.Talent(17793, 5),
	ImprovedShadowBoltTriggered: spelldata.Ranked(17794),
	ImprovedSpellstone:          spelldata.Ranked(18774, 18775),
	ImprovedSubjugateDemon:      spelldata.Ranked(18821, 18822, 18823, 18824, 18825),
	ImprovedVoidwalker:          spelldata.Talent(18705, 3),
	Incinerate:                  spelldata.Ranked(412758, 1293812, 1293813),
	Intensity:                   spelldata.Talent(18135, 3),
	LifeTap:                     spelldata.Ranked(1454, 1455, 1456, 11687, 11688, 11689),
	LifeTapTriggered:            spelldata.Ranked(18182),
	Malediction:                 spelldata.Talent(1225177, 5),
	Malevolence:                 spelldata.Talent(1310949, 5),
	MasterDemonologist:          spelldata.Talent(23785, 5),
	MasterSummoner:              spelldata.Talent(18709, 2),
	MetamorphosisDemonCharge:    spelldata.Ranked(412783),
	MoltenSkin:                  spelldata.Talent(1225220, 5),
	Nightfall:                   spelldata.Talent(18094, 2),
	NightfallTriggered:          spelldata.Ranked(17941),
	Pandemic:                    spelldata.Talent(427712, 3),
	PortalOfSummoning:           spelldata.Ranked(437169),
	Pyroclasm:                   spelldata.Talent(18073, 2),
	PyroclasmTriggered:          spelldata.Ranked(18093, 18350),
	RainOfFire:                  spelldata.Ranked(5740, 6219, 11677, 11678),
	RainOfFireTriggered:         spelldata.Ranked(1282380, 1282383, 1282384, 1282385),
	RitualOfDoom:                spelldata.Ranked(18540),
	RitualOfSummoning:           spelldata.Ranked(698),
	Ruin:                        spelldata.Talent(17959, 5),
	SearingPain:                 spelldata.Ranked(5676, 17919, 17920, 17921, 17922, 17923),
	SenseDemons:                 spelldata.Ranked(5500),
	ShadowBolt:                  spelldata.Ranked(686, 695, 705, 1088, 1106, 7641, 11659, 11660, 11661, 25307),
	ShadowCleave:                spelldata.Ranked(403835, 403839, 403840, 403841, 403842, 403843, 403844, 403848, 403851, 403852),
	ShadowCleaveTriggered:       spelldata.Ranked(460171, 460200),
	ShadowMastery:               spelldata.Talent(18271, 5),
	ShadowWard:                  spelldata.Ranked(6229, 11739, 11740, 28610),
	ShadowAndFlame:              spelldata.Talent(426316, 5),
	ShadowAndFlameTriggered:     spelldata.Ranked(426311, 1293816),
	Shadowburn:                  spelldata.Ranked(17877, 18867, 18868, 18869, 18870, 18871),
	SiphonLife:                  spelldata.Ranked(18265, 18879, 18880, 18881),
	SoulFire:                    spelldata.Ranked(6353, 17924),
	SoulHarvest:                 spelldata.Talent(437032, 2),
	SoulHarvestTriggered:        spelldata.Ranked(1242853),
	SoulLink:                    spelldata.Ranked(19028),
	SoulLinkTriggered:           spelldata.Ranked(18814, 25228),
	SoulSiphon:                  spelldata.Talent(17804, 3),
	SubjugateDemon:              spelldata.Ranked(1098, 11725, 11726),
	Suppression:                 spelldata.Talent(18174, 5),
	UnendingBreath:              spelldata.Ranked(5697),
	UnholyPower:                 spelldata.Talent(18769, 5),
	Wrack:                       spelldata.Ranked(1316697),
}
