// Code generated by tools/database/gen_spelldata. DO NOT EDIT.

import { Class, Stat } from '@generated/proto/common';
import { ActionId } from '@sim/proto/action_id';
import {
	makeBooleanDebuffInput,
	makeBooleanIndividualBuffInput,
	makeBooleanPartyBuffInput,
	makeBooleanRaidBuffInput,
	makeMultistateIndividualBuffInput,
	makeMultistatePartyBuffInput,
	makeTristatePartyBuffInput,
} from '@ui-kit/icon_inputs';

import type { RenderableStatOptions } from './stat_options';

export const BloodPact = makeBooleanPartyBuffInput({
	actionId: ActionId.fromSpellId(11767),
	fieldName: 'bloodPact',
	label: 'Blood Pact',
});

export const BattleShout = makeTristatePartyBuffInput({
	actionId: ActionId.fromSpellId(25289),
	impId: ActionId.fromSpellId(23563),
	fieldName: 'battleShout',
	label: 'Battle Shout',
});

export const DevotionAura = makeBooleanPartyBuffInput({
	actionId: ActionId.fromSpellId(10293),
	fieldName: 'devotionAura',
	label: 'Devotion Aura',
});

export const LeaderOfThePack = makeBooleanPartyBuffInput({
	actionId: ActionId.fromSpellId(24932),
	fieldName: 'leaderOfThePack',
	label: 'Leader of the Pack',
});

export const ManaSpringTotem = makeTristatePartyBuffInput({
	actionId: ActionId.fromSpellId(10494),
	impId: ActionId.fromSpellId(16187),
	fieldName: 'manaSpringTotem',
	label: 'Mana Spring Totem',
});

export const ManaTideTotems = makeMultistatePartyBuffInput({
	actionId: ActionId.fromSpellId(17360),
	numStates: 5,
	fieldName: 'manaTideTotems',
	label: 'Mana Tide Totem',
});

export const MoonkinAura = makeBooleanPartyBuffInput({
	actionId: ActionId.fromSpellId(24907),
	fieldName: 'moonkinAura',
	label: 'Moonkin Aura',
});

// retribution_aura: the hand-written input shows itself for tank specs only, since a damage shield only matters on the unit being hit; a role gate no manifest
// row carries.

// retribution_aura_spell_power: retired: Retribution Aura reads the spell power of the unit it is on, not the paladin's (beta logs 2729-2736), so nothing reads
// this; the row stays so the party fields after it keep their proto numbers.

export const ConcentrationAura = makeBooleanPartyBuffInput({
	actionId: ActionId.fromSpellId(19746),
	fieldName: 'concentrationAura',
	label: 'Concentration Aura',
});

export const TrueshotAura = makeBooleanPartyBuffInput({
	actionId: ActionId.fromSpellId(20905),
	fieldName: 'trueshotAura',
	label: 'Trueshot Aura',
});

export const AtieshMage = makeMultistatePartyBuffInput({
	actionId: ActionId.fromSpellId(28142),
	numStates: 5,
	fieldName: 'atieshMage',
	label: 'Atiesh - Mage',
});

export const AtieshWarlock = makeMultistatePartyBuffInput({
	actionId: ActionId.fromSpellId(28143),
	numStates: 5,
	fieldName: 'atieshWarlock',
	label: 'Atiesh - Warlock',
});

export const StrengthOfEarthTotem = makeBooleanPartyBuffInput({
	actionId: ActionId.fromSpellId(25362),
	fieldName: 'strengthOfEarthTotem',
	label: 'Strength of Earth Totem',
});

export const GraceOfAirTotem = makeBooleanPartyBuffInput({
	actionId: ActionId.fromSpellId(25360),
	fieldName: 'graceOfAirTotem',
	label: 'Grace of Air Totem',
});

export const WindfuryTotem = makeBooleanPartyBuffInput({
	actionId: ActionId.fromSpellId(10610),
	fieldName: 'windfuryTotem',
	label: 'Windfury Totem',
});

// atiesh_druid: no settings input over this field.

// atiesh_priest: no settings input over this field.

// totem_twisting: sim behaviour toggle with no spell source; rendered under Other Inputs.

export const FlametongueTotem = makeBooleanPartyBuffInput({
	actionId: ActionId.fromSpellId(15036),
	fieldName: 'flametongueTotem',
	label: 'Flametongue Totem',
});

export const ArcaneBrilliance = makeBooleanRaidBuffInput({
	actionId: ActionId.fromSpellId(23028),
	fieldName: 'arcaneBrilliance',
	label: 'Arcane Brilliance',
});

export const PrayerOfSpirit = makeBooleanRaidBuffInput({
	actionId: ActionId.fromSpellId(27681),
	fieldName: 'prayerOfSpirit',
	label: 'Prayer of Spirit',
});

export const GiftOfTheWild = makeBooleanRaidBuffInput({
	actionId: ActionId.fromSpellId(21850),
	fieldName: 'giftOfTheWild',
	label: 'Gift of the Wild',
});

export const Thorns = makeBooleanRaidBuffInput({
	actionId: ActionId.fromSpellId(9910),
	fieldName: 'thorns',
	label: 'Thorns',
});

export const PrayerOfFortitude = makeBooleanRaidBuffInput({
	actionId: ActionId.fromSpellId(21564),
	fieldName: 'prayerOfFortitude',
	label: 'Prayer of Fortitude',
});

export const PrayerOfShadowProtection = makeBooleanRaidBuffInput({
	actionId: ActionId.fromSpellId(27683),
	fieldName: 'prayerOfShadowProtection',
	label: 'Prayer of Shadow Protection',
});

export const FireResistanceAura = makeBooleanRaidBuffInput({
	actionId: ActionId.fromSpellId(19900),
	fieldName: 'fireResistanceAura',
	label: 'Fire Resistance Aura',
});

export const FrostResistanceAura = makeBooleanRaidBuffInput({
	actionId: ActionId.fromSpellId(19898),
	fieldName: 'frostResistanceAura',
	label: 'Frost Resistance Aura',
});

export const ShadowResistanceAura = makeBooleanRaidBuffInput({
	actionId: ActionId.fromSpellId(19896),
	fieldName: 'shadowResistanceAura',
	label: 'Shadow Resistance Aura',
});

export const FireResistanceTotem = makeBooleanRaidBuffInput({
	actionId: ActionId.fromSpellId(10535),
	fieldName: 'fireResistanceTotem',
	label: 'Fire Resistance Totem',
});

export const FrostResistanceTotem = makeBooleanRaidBuffInput({
	actionId: ActionId.fromSpellId(10477),
	fieldName: 'frostResistanceTotem',
	label: 'Frost Resistance Totem',
});

export const NatureResistanceTotem = makeBooleanRaidBuffInput({
	actionId: ActionId.fromSpellId(10599),
	fieldName: 'natureResistanceTotem',
	label: 'Nature Resistance Totem',
});

export const AspectOfTheWild = makeBooleanRaidBuffInput({
	actionId: ActionId.fromSpellId(20190),
	fieldName: 'aspectOfTheWild',
	label: 'Aspect of the Wild',
});

export const GreaterBlessingOfKings = makeBooleanIndividualBuffInput({
	actionId: ActionId.fromSpellId(25898),
	fieldName: 'greaterBlessingOfKings',
	label: 'Greater Blessing of Kings',
});

export const GreaterBlessingOfMight = makeBooleanIndividualBuffInput({
	actionId: ActionId.fromSpellId(25916),
	fieldName: 'greaterBlessingOfMight',
	label: 'Greater Blessing of Might',
});

export const GreaterBlessingOfWisdom = makeBooleanIndividualBuffInput({
	actionId: ActionId.fromSpellId(25918),
	fieldName: 'greaterBlessingOfWisdom',
	label: 'Greater Blessing of Wisdom',
});

// greater_blessing_of_salvation: the hand-written input hides itself for tank and healing specs, a role gate no manifest row carries.

// greater_blessing_of_light: the hand-written input shows itself for tank and healing specs only, a role gate no manifest row carries.

export const Innervates = makeMultistateIndividualBuffInput({
	actionId: ActionId.fromSpellId(29166),
	numStates: 11,
	fieldName: 'innervates',
	label: 'Innervates',
});

export const PowerInfusions = makeMultistateIndividualBuffInput({
	actionId: ActionId.fromSpellId(10060),
	numStates: 11,
	fieldName: 'powerInfusions',
	label: 'Power Infusions',
});

export const HuntersMark = makeBooleanDebuffInput({
	actionId: ActionId.fromSpellId(14325),
	fieldName: 'huntersMark',
	label: "Hunter's Mark",
});

export const JudgementOfTheCrusader = makeBooleanDebuffInput({
	actionId: ActionId.fromSpellId(20303),
	fieldName: 'judgementOfTheCrusader',
	label: 'Judgement of the Crusader',
});

export const JudgementOfLight = makeBooleanDebuffInput({
	actionId: ActionId.fromSpellId(20346),
	fieldName: 'judgementOfLight',
	label: 'Judgement of Light',
});

export const JudgementOfWisdom = makeBooleanDebuffInput({
	actionId: ActionId.fromSpellId(20355),
	fieldName: 'judgementOfWisdom',
	label: 'Judgement of Wisdom',
});

export const CurseOfElements = makeBooleanDebuffInput({
	actionId: ActionId.fromSpellId(1311680),
	fieldName: 'curseOfElements',
	label: 'Curse of the Elements',
});

export const CurseOfRecklessness = makeBooleanDebuffInput({
	actionId: ActionId.fromSpellId(11717),
	fieldName: 'curseOfRecklessness',
	label: 'Curse of Recklessness',
});

export const FaerieFire = makeBooleanDebuffInput({
	actionId: ActionId.fromSpellId(9907),
	fieldName: 'faerieFire',
	label: 'Faerie Fire',
});

export const ExposeArmor = makeBooleanDebuffInput({
	actionId: ActionId.fromSpellId(11198),
	fieldName: 'exposeArmor',
	label: 'Expose Armor',
});

export const SunderArmor = makeBooleanDebuffInput({
	actionId: ActionId.fromSpellId(11597),
	fieldName: 'sunderArmor',
	label: 'Sunder Armor',
});

export const GiftOfArthas = makeBooleanDebuffInput({
	actionId: ActionId.fromSpellId(11374),
	fieldName: 'giftOfArthas',
	label: 'Gift of Arthas',
});

export const DemoralizingRoar = makeBooleanDebuffInput({
	actionId: ActionId.fromSpellId(9898),
	fieldName: 'demoralizingRoar',
	label: 'Demoralizing Roar',
});

export const DemoralizingShout = makeBooleanDebuffInput({
	actionId: ActionId.fromSpellId(11556),
	fieldName: 'demoralizingShout',
	label: 'Demoralizing Shout',
});

export const ThunderClap = makeBooleanDebuffInput({
	actionId: ActionId.fromSpellId(11581),
	fieldName: 'thunderClap',
	label: 'Thunder Clap',
});

export const InsectSwarm = makeBooleanDebuffInput({
	actionId: ActionId.fromSpellId(24977),
	fieldName: 'insectSwarm',
	label: 'Insect Swarm',
});

export const ScorpidSting = makeBooleanDebuffInput({
	actionId: ActionId.fromSpellId(3043),
	fieldName: 'scorpidSting',
	label: 'Scorpid Sting',
});

export const GENERATED_RAID_BUFFS_CONFIG: RenderableStatOptions[] = [
	{
		config: ArcaneBrilliance,
		stats: [Stat.StatIntellect],
		ownerClass: Class.ClassMage,
	},
	{
		config: PrayerOfSpirit,
		stats: [Stat.StatSpirit, Stat.StatSpellDamage],
		ownerClass: Class.ClassPriest,
	},
	{
		config: GiftOfTheWild,
		stats: [Stat.StatArmor, Stat.StatStrength, Stat.StatAgility, Stat.StatIntellect, Stat.StatSpirit, Stat.StatStamina],
		ownerClass: Class.ClassDruid,
	},
	{
		config: Thorns,
		stats: [Stat.StatDefenseRating, Stat.StatStamina],
		ownerClass: Class.ClassDruid,
	},
	{
		config: PrayerOfFortitude,
		stats: [Stat.StatStamina],
		ownerClass: Class.ClassPriest,
	},
	{
		config: PrayerOfShadowProtection,
		stats: [Stat.StatShadowResistance, Stat.StatStamina],
		ownerClass: Class.ClassPriest,
	},
	{
		config: FireResistanceAura,
		stats: [Stat.StatFireResistance],
		ownerClass: Class.ClassPaladin,
	},
	{
		config: FrostResistanceAura,
		stats: [Stat.StatFrostResistance],
		ownerClass: Class.ClassPaladin,
	},
	{
		config: ShadowResistanceAura,
		stats: [Stat.StatShadowResistance],
		ownerClass: Class.ClassPaladin,
	},
	{
		config: FireResistanceTotem,
		stats: [Stat.StatFireResistance],
		ownerClass: Class.ClassShaman,
	},
	{
		config: FrostResistanceTotem,
		stats: [Stat.StatFrostResistance],
		ownerClass: Class.ClassShaman,
	},
	{
		config: NatureResistanceTotem,
		stats: [Stat.StatNatureResistance],
		ownerClass: Class.ClassShaman,
	},
	{
		config: AspectOfTheWild,
		stats: [Stat.StatNatureResistance],
		ownerClass: Class.ClassHunter,
	},
];

export const GENERATED_PARTY_BUFFS_CONFIG: RenderableStatOptions[] = [
	{
		config: BloodPact,
		stats: [Stat.StatStamina],
		ownerClass: Class.ClassWarlock,
	},
	{
		config: BattleShout,
		stats: [Stat.StatAttackPower],
		ownerClass: Class.ClassWarrior,
	},
	{
		config: DevotionAura,
		stats: [Stat.StatArmor],
		ownerClass: Class.ClassPaladin,
	},
	{
		config: LeaderOfThePack,
		stats: [Stat.StatMeleeCritRating, Stat.StatSpellCritRating],
		ownerClass: Class.ClassDruid,
	},
	{
		config: ManaSpringTotem,
		stats: [Stat.StatMP5],
		ownerClass: Class.ClassShaman,
	},
	{
		config: ManaTideTotems,
		stats: [Stat.StatMP5],
		ownerClass: Class.ClassShaman,
	},
	{
		config: MoonkinAura,
		stats: [Stat.StatMeleeCritRating, Stat.StatSpellCritRating],
		ownerClass: Class.ClassDruid,
	},
	{
		config: ConcentrationAura,
		stats: [Stat.StatDefenseRating],
		ownerClass: Class.ClassPaladin,
	},
	{
		config: TrueshotAura,
		stats: [Stat.StatRangedAttackPower],
		ownerClass: Class.ClassHunter,
	},
	{
		config: AtieshMage,
		stats: [Stat.StatSpellDamage, Stat.StatHealingPower],
		ownerClass: Class.ClassMage,
	},
	{
		config: AtieshWarlock,
		stats: [Stat.StatSpellDamage, Stat.StatHealingPower],
		ownerClass: Class.ClassWarlock,
	},
	{
		config: StrengthOfEarthTotem,
		stats: [Stat.StatStrength],
		ownerClass: Class.ClassShaman,
	},
	{
		config: GraceOfAirTotem,
		stats: [Stat.StatAgility],
		ownerClass: Class.ClassShaman,
	},
	{
		config: WindfuryTotem,
		stats: [Stat.StatAttackPower],
		ownerClass: Class.ClassShaman,
	},
	{
		config: FlametongueTotem,
		stats: [],
		ownerClass: Class.ClassShaman,
	},
];

export const GENERATED_INDIVIDUAL_BUFFS_CONFIG: RenderableStatOptions[] = [
	{
		config: GreaterBlessingOfKings,
		stats: [Stat.StatAgility, Stat.StatIntellect, Stat.StatSpirit, Stat.StatStamina, Stat.StatStrength],
		ownerClass: Class.ClassPaladin,
	},
	{
		config: GreaterBlessingOfMight,
		stats: [Stat.StatAttackPower],
		ownerClass: Class.ClassPaladin,
	},
	{
		config: GreaterBlessingOfWisdom,
		stats: [Stat.StatMP5],
		ownerClass: Class.ClassPaladin,
	},
	{
		config: Innervates,
		stats: [Stat.StatMP5],
		ownerClass: Class.ClassDruid,
	},
	{
		config: PowerInfusions,
		stats: [Stat.StatSpellHasteRating],
		ownerClass: Class.ClassPriest,
	},
];

export const GENERATED_DEBUFFS_CONFIG: RenderableStatOptions[] = [
	{
		config: HuntersMark,
		stats: [Stat.StatRangedAttackPower, Stat.StatAttackPower],
		ownerClass: Class.ClassHunter,
	},
	{
		config: JudgementOfTheCrusader,
		stats: [Stat.StatHolyDamage, Stat.StatSpellDamage],
		ownerClass: Class.ClassPaladin,
	},
	{
		config: JudgementOfLight,
		stats: [Stat.StatDefenseRating],
		ownerClass: Class.ClassPaladin,
	},
	{
		config: JudgementOfWisdom,
		stats: [Stat.StatMP5],
		ownerClass: Class.ClassPaladin,
	},
	{
		config: CurseOfElements,
		stats: [Stat.StatSpellDamage],
		ownerClass: Class.ClassWarlock,
	},
	{
		config: CurseOfRecklessness,
		stats: [Stat.StatAttackPower],
		ownerClass: Class.ClassWarlock,
	},
	{
		config: FaerieFire,
		stats: [Stat.StatAttackPower, Stat.StatMeleeHitRating],
		ownerClass: Class.ClassDruid,
	},
	{
		config: ExposeArmor,
		stats: [Stat.StatAttackPower],
		ownerClass: Class.ClassRogue,
	},
	{
		config: SunderArmor,
		stats: [Stat.StatAttackPower],
		ownerClass: Class.ClassWarrior,
	},
	{
		config: GiftOfArthas,
		stats: [Stat.StatAttackPower, Stat.StatDefenseRating],
	},
	{
		config: DemoralizingRoar,
		stats: [Stat.StatStamina, Stat.StatDefenseRating],
		ownerClass: Class.ClassDruid,
	},
	{
		config: DemoralizingShout,
		stats: [Stat.StatStamina, Stat.StatDefenseRating],
		ownerClass: Class.ClassWarrior,
	},
	{
		config: ThunderClap,
		stats: [Stat.StatStamina, Stat.StatDefenseRating],
		ownerClass: Class.ClassWarrior,
	},
	{
		config: InsectSwarm,
		stats: [Stat.StatStamina, Stat.StatDefenseRating],
		ownerClass: Class.ClassDruid,
	},
	{
		config: ScorpidSting,
		stats: [Stat.StatStamina, Stat.StatDefenseRating],
		ownerClass: Class.ClassHunter,
	},
];
