// Code generated by tools/database/gen_spelldata. DO NOT EDIT.

package hunter

import (
	"github.com/wowsims/forever/sim/core/spelldata"
)

// Not generated:
//   Monster Slaying: missing rank 1 of 3
//   Natural Armor: ambiguous rank 1 between spells 24545, 24547; rank 2 between spells 24549, 24556; rank 3 between spells 24550, 24557; rank 4 between spells 24551, 24558; rank 5 between spells 24552, 24559; rank 6 between spells 24553, 24560; rank 7 between spells 24554, 24561; rank 8 between spells 24555, 24562

// Generated with an effect held at its base points, the talent tree stating no rank value for it:
//   Barrage: effect 1 of spell 19461 has no rank curve and is held at its base points
//   Improved Serpent Sting: effect 1 of spell 19464 has no rank curve and is held at its base points
//   Lacerating Strikes: effect 0 of spell 1310533 has no rank curve and is held at its base points
//   Lone Wolf: effect 0, 1 of spell 415370 has no rank curve and is held at its base points
//   Surefooted: effect 3 of spell 19290 has no rank curve and is held at its base points

type generatedSpellData struct {
	AimedShot                       spelldata.Ladder
	ArcaneResistance                spelldata.Ladder
	ArcaneResistanceTriggered       spelldata.Ladder
	ArcaneShot                      spelldata.Ladder
	AspectOfTheBeast                spelldata.Ladder
	AspectOfTheBeastTriggered       spelldata.Ladder
	AspectOfTheCheetah              spelldata.Ladder
	AspectOfTheCheetahTriggered     spelldata.Ladder
	AspectOfTheFalcon               spelldata.Ladder
	AspectOfTheFalconTriggered      spelldata.Ladder
	AspectOfTheHawk                 spelldata.Ladder
	AspectOfTheHawkTriggered        spelldata.Ladder
	AspectOfTheMonkey               spelldata.Ladder
	AspectOfThePack                 spelldata.Ladder
	AspectOfThePackTriggered        spelldata.Ladder
	AspectOfTheViper                spelldata.Ladder
	AspectOfTheWild                 spelldata.Ladder
	AutoShot                        spelldata.Ladder
	Barrage                         spelldata.Ladder
	BeastLore                       spelldata.Ladder
	BeastTraining                   spelldata.Ladder
	BestialDiscipline               spelldata.Ladder
	BestialSwiftness                spelldata.Ladder
	BestialWrath                    spelldata.Ladder
	Bite                            spelldata.Ladder
	BiteTriggered                   spelldata.Ladder
	BlackArrow                      spelldata.Ladder
	CallPet                         spelldata.Ladder
	CarefulAim                      spelldata.Ladder
	Charge                          spelldata.Ladder
	ChargeTriggered                 spelldata.Ladder
	Claw                            spelldata.Ladder
	ClawTriggered                   spelldata.Ladder
	CleverTraps                     spelldata.Ladder
	CobraReflexes                   spelldata.Ladder
	CobraReflexesTriggered          spelldata.Ladder
	ConcussiveShot                  spelldata.Ladder
	Counterattack                   spelldata.Ladder
	Cower                           spelldata.Ladder
	CowerTriggered                  spelldata.Ladder
	Dash                            spelldata.Ladder
	DashTriggered                   spelldata.Ladder
	DeadlyAspects                   spelldata.Ladder
	DeadlyAspectsTriggered          spelldata.Ladder
	DefensiveState                  spelldata.Ladder
	DefensiveStateTriggered         spelldata.Ladder
	DefensiveState2                 spelldata.Ladder
	DefensiveState2Triggered        spelldata.Ladder
	Deflection                      spelldata.Ladder
	DemoralizingScreech             spelldata.Ladder
	DemoralizingScreechTriggered    spelldata.Ladder
	Deterrence                      spelldata.Ladder
	Disengage                       spelldata.Ladder
	Dismember                       spelldata.Ladder
	DismemberTriggered              spelldata.Ladder
	DismissPet                      spelldata.Ladder
	DistractingShot                 spelldata.Ladder
	Dive                            spelldata.Ladder
	DiveTriggered                   spelldata.Ladder
	DustCloud                       spelldata.Ladder
	DustCloudTriggered              spelldata.Ladder
	EagleEye                        spelldata.Ladder
	Efficiency                      spelldata.Ladder
	EnchantedFlare                  spelldata.Ladder
	EnchantedFlareTriggered         spelldata.Ladder
	EnduranceTraining               spelldata.Ladder
	Entrapment                      spelldata.Ladder
	ExplosiveTrap                   spelldata.Ladder
	ExplosiveTrapTriggered          spelldata.Ladder
	ExplosiveTrapEffect             spelldata.Ladder
	ExposePrey                      spelldata.Ladder
	ExposePreyTriggered             spelldata.Ladder
	EyesOfTheBeast                  spelldata.Ladder
	FasterAttackI                   spelldata.Ladder
	FasterAttackII                  spelldata.Ladder
	FasterAttackIII                 spelldata.Ladder
	FasterAttackIV                  spelldata.Ladder
	FasterAttackV                   spelldata.Ladder
	FasterAttackVI                  spelldata.Ladder
	FasterAttackVII                 spelldata.Ladder
	FeedPet                         spelldata.Ladder
	FeedPetTriggered                spelldata.Ladder
	FeignDeath                      spelldata.Ladder
	Ferocity                        spelldata.Ladder
	FireResistance                  spelldata.Ladder
	FireResistanceTriggered         spelldata.Ladder
	Flare                           spelldata.Ladder
	FocusedFire                     spelldata.Ladder
	FreezingTrap                    spelldata.Ladder
	FreezingTrapTriggered           spelldata.Ladder
	Frenzy                          spelldata.Ladder
	FrenzyTriggered                 spelldata.Ladder
	FrostResistance                 spelldata.Ladder
	FrostResistanceTriggered        spelldata.Ladder
	FrostTrap                       spelldata.Ladder
	FrostTrapTriggered              spelldata.Ladder
	FuriousHowl                     spelldata.Ladder
	FuriousHowlTriggered            spelldata.Ladder
	GreatStamina                    spelldata.Ladder
	GreatStaminaTriggered           spelldata.Ladder
	Growl                           spelldata.Ladder
	GrowlTriggered                  spelldata.Ladder
	Harass                          spelldata.Ladder
	HarassTriggered                 spelldata.Ladder
	HawkEye                         spelldata.Ladder
	HeartOfTheLion                  spelldata.Ladder
	HeartOfTheLionTriggered         spelldata.Ladder
	HumanoidSlaying                 spelldata.Ladder
	HuntersMark                     spelldata.Ladder
	ImmolationTrap                  spelldata.Ladder
	ImmolationTrapTriggered         spelldata.Ladder
	ImprovedArcaneShot              spelldata.Ladder
	ImprovedAspectOfTheMonkey       spelldata.Ladder
	ImprovedConcussiveShot          spelldata.Ladder
	ImprovedConcussiveShotTriggered spelldata.Ladder
	ImprovedEyesOfTheBeast          spelldata.Ladder
	ImprovedFeignDeath              spelldata.Ladder
	ImprovedMendPet                 spelldata.Ladder
	ImprovedMendPetTriggered        spelldata.Ladder
	ImprovedRevivePet               spelldata.Ladder
	ImprovedSerpentSting            spelldata.Ladder
	ImprovedStings                  spelldata.Ladder
	ImprovedTracking                spelldata.Ladder
	ImprovedWingClip                spelldata.Ladder
	ImprovedWingClipTriggered       spelldata.Ladder
	Intimidation                    spelldata.Ladder
	IntimidationTriggered           spelldata.Ladder
	Lacerate                        spelldata.Ladder
	LaceratingStrikes               spelldata.Ladder
	LaceratingStrikesTriggered      spelldata.Ladder
	LavaBreath                      spelldata.Ladder
	LavaBreathTriggered             spelldata.Ladder
	LethalAttacks                   spelldata.Ladder
	LightningBreath                 spelldata.Ladder
	LightningBreathTriggered        spelldata.Ladder
	LightningReflexes               spelldata.Ladder
	LoneWolf                        spelldata.Ladder
	MeleeSpecialization             spelldata.Ladder
	MendPet                         spelldata.Ladder
	Mine                            spelldata.Ladder
	MineTriggered                   spelldata.Ladder
	MongooseBite                    spelldata.Ladder
	MortalShots                     spelldata.Ladder
	MultiShot                       spelldata.Ladder
	NatureResistance                spelldata.Ladder
	NatureResistanceTriggered       spelldata.Ladder
	Pathfinding                     spelldata.Ladder
	PetAggression                   spelldata.Ladder
	PetHardiness                    spelldata.Ladder
	PetRecovery                     spelldata.Ladder
	PetResistance                   spelldata.Ladder
	Pinch                           spelldata.Ladder
	PinchTriggered                  spelldata.Ladder
	PredatorsEdge                   spelldata.Ladder
	Prowl                           spelldata.Ladder
	ProwlTriggered                  spelldata.Ladder
	RangedWeaponSpecialization      spelldata.Ladder
	RapidFire                       spelldata.Ladder
	RapidKilling                    spelldata.Ladder
	RapidKillingTriggered           spelldata.Ladder
	RapidRecuperation               spelldata.Ladder
	RapidRecuperationTriggered      spelldata.Ladder
	RaptorStrike                    spelldata.Ladder
	Resourcefulness                 spelldata.Ladder
	ResourcefulnessTriggered        spelldata.Ladder
	RevivePet                       spelldata.Ladder
	SavageRend                      spelldata.Ladder
	SavageRendTriggered             spelldata.Ladder
	SavageStrikes                   spelldata.Ladder
	ScareBeast                      spelldata.Ladder
	ScatterShot                     spelldata.Ladder
	ScorpidPoison                   spelldata.Ladder
	ScorpidPoisonTriggered          spelldata.Ladder
	ScorpidSting                    spelldata.Ladder
	SerpentSting                    spelldata.Ladder
	ShadowResistance                spelldata.Ladder
	ShadowResistanceTriggered       spelldata.Ladder
	ShellShield                     spelldata.Ladder
	ShellShieldTriggered            spelldata.Ladder
	SlowerAttackII                  spelldata.Ladder
	SlowerAttackIII                 spelldata.Ladder
	SniperShot                      spelldata.Ladder
	SpiritBond                      spelldata.Ladder
	StriderKick                     spelldata.Ladder
	SummonHawk                      spelldata.Ladder
	SummonHawkTriggered             spelldata.Ladder
	Surefooted                      spelldata.Ladder
	SurvivalTactics                 spelldata.Ladder
	Survivalist                     spelldata.Ladder
	SurvivalistsDiscipline          spelldata.Ladder
	Swipe                           spelldata.Ladder
	SwipeTriggered                  spelldata.Ladder
	TameBeast                       spelldata.Ladder
	TameBeastTriggered              spelldata.Ladder
	TendonRip                       spelldata.Ladder
	TendonRipTriggered              spelldata.Ladder
	Thunderstomp                    spelldata.Ladder
	ThunderstompTriggered           spelldata.Ladder
	TrackBeasts                     spelldata.Ladder
	TrackDemons                     spelldata.Ladder
	TrackDragonkin                  spelldata.Ladder
	TrackElementals                 spelldata.Ladder
	TrackGiants                     spelldata.Ladder
	TrackHidden                     spelldata.Ladder
	TrackHumanoids                  spelldata.Ladder
	TrackUndead                     spelldata.Ladder
	TranquilizingShot               spelldata.Ladder
	TrickstersDance                 spelldata.Ladder
	TrickstersDanceTriggered        spelldata.Ladder
	TrueshotAura                    spelldata.Ladder
	UnleashedFury                   spelldata.Ladder
	ViperSting                      spelldata.Ladder
	Volley                          spelldata.Ladder
	VolleyTriggered                 spelldata.Ladder
	Web                             spelldata.Ladder
	WebTriggered                    spelldata.Ladder
	WingClip                        spelldata.Ladder
}

var spellData = generatedSpellData{
	AimedShot:                       spelldata.Ranked(19434, 20900, 20901, 20902, 20903, 20904),
	ArcaneResistance:                spelldata.Ranked(24495, 24508, 24509, 24510),
	ArcaneResistanceTriggered:       spelldata.Ranked(24493, 24497, 24500, 24501),
	ArcaneShot:                      spelldata.Ranked(3044, 14281, 14282, 14283, 14284, 14285, 14286, 14287),
	AspectOfTheBeast:                spelldata.Ranked(13161, 1299445, 1299446, 1299447),
	AspectOfTheBeastTriggered:       spelldata.Ranked(1299448),
	AspectOfTheCheetah:              spelldata.Ranked(5118),
	AspectOfTheCheetahTriggered:     spelldata.Ranked(15571),
	AspectOfTheFalcon:               spelldata.Ranked(469145),
	AspectOfTheFalconTriggered:      spelldata.Ranked(469144),
	AspectOfTheHawk:                 spelldata.Ranked(13165, 14318, 14319, 14320, 14321, 14322, 25296),
	AspectOfTheHawkTriggered:        spelldata.Ranked(6150),
	AspectOfTheMonkey:               spelldata.Ranked(13163),
	AspectOfThePack:                 spelldata.Ranked(13159),
	AspectOfThePackTriggered:        spelldata.Ranked(15571),
	AspectOfTheViper:                spelldata.Ranked(415423),
	AspectOfTheWild:                 spelldata.Ranked(20043, 20190),
	AutoShot:                        spelldata.Ranked(75),
	Barrage:                         spelldata.Talent(19461, 3),
	BeastLore:                       spelldata.Ranked(1462),
	BeastTraining:                   spelldata.Ranked(5149),
	BestialDiscipline:               spelldata.Talent(19590, 2),
	BestialSwiftness:                spelldata.Ranked(19596),
	BestialWrath:                    spelldata.Ranked(19574),
	Bite:                            spelldata.Ranked(17254, 17262, 17263, 17264, 17265, 17266, 17267, 17268),
	BiteTriggered:                   spelldata.Ranked(17253, 17255, 17256, 17257, 17258, 17259, 17260, 17261),
	BlackArrow:                      spelldata.Ranked(3674, 14296),
	CallPet:                         spelldata.Ranked(883),
	CarefulAim:                      spelldata.Talent(1223984, 5),
	Charge:                          spelldata.Ranked(7370, 26184, 26185, 26186, 26202, 28343),
	ChargeTriggered:                 spelldata.Ranked(7371, 26177, 26178, 26179, 26201, 27685),
	Claw:                            spelldata.Ranked(2980, 2981, 2982, 3667, 2975, 2976, 2977, 3666),
	ClawTriggered:                   spelldata.Ranked(16827, 16828, 16829, 16830, 16831, 16832, 3010, 3009),
	CleverTraps:                     spelldata.Talent(19239, 2),
	CobraReflexes:                   spelldata.Ranked(25077),
	CobraReflexesTriggered:          spelldata.Ranked(25076),
	ConcussiveShot:                  spelldata.Ranked(5116),
	Counterattack:                   spelldata.Ranked(19306, 1242634, 20909, 20910),
	Cower:                           spelldata.Ranked(1747, 1748, 1749, 1750, 1751, 16698),
	CowerTriggered:                  spelldata.Ranked(1742, 1753, 1754, 1755, 1756, 16697),
	Dash:                            spelldata.Ranked(23100, 23111, 23112),
	DashTriggered:                   spelldata.Ranked(23099, 23109, 23110),
	DeadlyAspects:                   spelldata.Talent(19552, 5),
	DeadlyAspectsTriggered:          spelldata.Ranked(6150, 1299448),
	DefensiveState:                  spelldata.Ranked(13358),
	DefensiveStateTriggered:         spelldata.Ranked(5302),
	DefensiveState2:                 spelldata.Ranked(24949),
	DefensiveState2Triggered:        spelldata.Ranked(24948),
	Deflection:                      spelldata.Talent(19295, 5),
	DemoralizingScreech:             spelldata.Ranked(24424, 24580, 24581, 24582),
	DemoralizingScreechTriggered:    spelldata.Ranked(24423, 24577, 24578, 24579),
	Deterrence:                      spelldata.Ranked(19263),
	Disengage:                       spelldata.Ranked(781, 14272, 14273),
	Dismember:                       spelldata.Ranked(1264937, 1264939, 1264970, 1264971, 1264972),
	DismemberTriggered:              spelldata.Ranked(1264758, 1264927, 1264929, 1264930, 1264933),
	DismissPet:                      spelldata.Ranked(2641),
	DistractingShot:                 spelldata.Ranked(20736, 14274, 15629, 15630, 15631, 15632),
	Dive:                            spelldata.Ranked(23146, 23149, 23150),
	DiveTriggered:                   spelldata.Ranked(23145, 23147, 23148),
	DustCloud:                       spelldata.Ranked(1265907, 1265908, 1265909, 1265913, 1265911),
	DustCloudTriggered:              spelldata.Ranked(1265899, 1265901, 1265902, 1265903, 1265904),
	EagleEye:                        spelldata.Ranked(6197),
	Efficiency:                      spelldata.Talent(19416, 5),
	EnchantedFlare:                  spelldata.Ranked(1221404),
	EnchantedFlareTriggered:         spelldata.Ranked(1221416),
	EnduranceTraining:               spelldata.Talent(19583, 5),
	Entrapment:                      spelldata.Talent(19184, 5),
	ExplosiveTrap:                   spelldata.Ranked(13813, 14316, 14317),
	ExplosiveTrapTriggered:          spelldata.Ranked(13812, 14314, 14315),
	ExplosiveTrapEffect:             spelldata.Ranked(13812, 14314, 14315),
	ExposePrey:                      spelldata.Talent(1310532, 2),
	ExposePreyTriggered:             spelldata.Ranked(1310726),
	EyesOfTheBeast:                  spelldata.Ranked(1002),
	FasterAttackI:                   spelldata.Ranked(1263099),
	FasterAttackII:                  spelldata.Ranked(1263100),
	FasterAttackIII:                 spelldata.Ranked(1263102),
	FasterAttackIV:                  spelldata.Ranked(1263104),
	FasterAttackV:                   spelldata.Ranked(1263107),
	FasterAttackVI:                  spelldata.Ranked(1263109),
	FasterAttackVII:                 spelldata.Ranked(1263110),
	FeedPet:                         spelldata.Ranked(6991),
	FeedPetTriggered:                spelldata.Ranked(1539),
	FeignDeath:                      spelldata.Ranked(5384),
	Ferocity:                        spelldata.Talent(19598, 5),
	FireResistance:                  spelldata.Ranked(24440, 24441, 24463, 24464),
	FireResistanceTriggered:         spelldata.Ranked(23992, 24439, 24444, 24445),
	Flare:                           spelldata.Ranked(1543),
	FocusedFire:                     spelldata.Talent(1223755, 2),
	FreezingTrap:                    spelldata.Ranked(1499, 14310, 14311),
	FreezingTrapTriggered:           spelldata.Ranked(3355, 14308, 14309),
	Frenzy:                          spelldata.Talent(19621, 5),
	FrenzyTriggered:                 spelldata.Ranked(19615),
	FrostResistance:                 spelldata.Ranked(24475, 24476, 24477, 24478),
	FrostResistanceTriggered:        spelldata.Ranked(24446, 24447, 24448, 24449),
	FrostTrap:                       spelldata.Ranked(13809),
	FrostTrapTriggered:              spelldata.Ranked(13810, 14207),
	FuriousHowl:                     spelldata.Ranked(24609, 24608, 24607, 24599),
	FuriousHowlTriggered:            spelldata.Ranked(24604, 24605, 24603, 24597),
	GreatStamina:                    spelldata.Ranked(4195, 4196, 4197, 4198, 4199, 4200, 4201, 4202, 5048, 5049),
	GreatStaminaTriggered:           spelldata.Ranked(4187, 4188, 4189, 4190, 4191, 4192, 4193, 4194, 5041, 5042),
	Growl:                           spelldata.Ranked(1853, 14922, 14923, 14924, 14925, 14926, 14927),
	GrowlTriggered:                  spelldata.Ranked(2649, 14916, 14917, 14918, 14919, 14920, 14921),
	Harass:                          spelldata.Ranked(23163, 23166, 23167),
	HarassTriggered:                 spelldata.Ranked(23162, 23164, 23165),
	HawkEye:                         spelldata.Talent(19498, 3),
	HeartOfTheLion:                  spelldata.Ranked(409580),
	HeartOfTheLionTriggered:         spelldata.Ranked(409583),
	HumanoidSlaying:                 spelldata.Ranked(19151, 19152, 19153),
	HuntersMark:                     spelldata.Ranked(1130, 14323, 14324, 14325),
	ImmolationTrap:                  spelldata.Ranked(13795, 14302, 14303, 14304, 14305),
	ImmolationTrapTriggered:         spelldata.Ranked(13797, 14298, 14299, 14300, 14301),
	ImprovedArcaneShot:              spelldata.Talent(19454, 5),
	ImprovedAspectOfTheMonkey:       spelldata.Talent(19549, 3),
	ImprovedConcussiveShot:          spelldata.Talent(19407, 5),
	ImprovedConcussiveShotTriggered: spelldata.Ranked(19410),
	ImprovedEyesOfTheBeast:          spelldata.Ranked(19557, 19558),
	ImprovedFeignDeath:              spelldata.Ranked(19286, 19287),
	ImprovedMendPet:                 spelldata.Talent(19572, 2),
	ImprovedMendPetTriggered:        spelldata.Ranked(24406),
	ImprovedRevivePet:               spelldata.Talent(24443, 2),
	ImprovedSerpentSting:            spelldata.Talent(19464, 5),
	ImprovedStings:                  spelldata.Talent(1310661, 3),
	ImprovedTracking:                spelldata.Talent(24293, 5),
	ImprovedWingClip:                spelldata.Talent(19228, 3),
	ImprovedWingClipTriggered:       spelldata.Ranked(19229),
	Intimidation:                    spelldata.Ranked(19577),
	IntimidationTriggered:           spelldata.Ranked(24394),
	Lacerate:                        spelldata.Ranked(24118, 24119, 24120, 1299332),
	LaceratingStrikes:               spelldata.Talent(1310533, 1),
	LaceratingStrikesTriggered:      spelldata.Ranked(1310536),
	LavaBreath:                      spelldata.Ranked(444680, 444682),
	LavaBreathTriggered:             spelldata.Ranked(444678, 444681),
	LethalAttacks:                   spelldata.Talent(19426, 5),
	LightningBreath:                 spelldata.Ranked(24845, 25013, 25014, 25015, 25016, 25017),
	LightningBreathTriggered:        spelldata.Ranked(24844, 25008, 25009, 25010, 25011, 25012),
	LightningReflexes:               spelldata.Talent(19168, 5),
	LoneWolf:                        spelldata.Talent(415370, 1),
	MeleeSpecialization:             spelldata.Ranked(19381, 19382, 19383, 19384, 19385),
	MendPet:                         spelldata.Ranked(136, 3111, 3661, 3662, 13542, 13543, 13544),
	Mine:                            spelldata.Ranked(1265059, 1265060, 1265061, 1265062, 1265064),
	MineTriggered:                   spelldata.Ranked(1265054, 1265055, 1265056, 1265057, 1265058),
	MongooseBite:                    spelldata.Ranked(1495, 14269, 14270, 14271),
	MortalShots:                     spelldata.Talent(19485, 5),
	MultiShot:                       spelldata.Ranked(2643),
	NatureResistance:                spelldata.Ranked(24494, 24511, 24512, 24513),
	NatureResistanceTriggered:       spelldata.Ranked(24492, 24502, 24503, 24504),
	Pathfinding:                     spelldata.Talent(19559, 2),
	PetAggression:                   spelldata.Ranked(6311, 6314, 6315, 6316, 6317),
	PetHardiness:                    spelldata.Ranked(6280, 6281, 6282, 6283, 6286),
	PetRecovery:                     spelldata.Ranked(6328, 6331, 6332, 6333, 6334),
	PetResistance:                   spelldata.Ranked(6443, 6444, 6445, 6446, 6447),
	Pinch:                           spelldata.Ranked(1264745, 1264749, 1264750, 1264751, 1264752),
	PinchTriggered:                  spelldata.Ranked(1264735, 1264736, 1264739, 1264741, 1264742),
	PredatorsEdge:                   spelldata.Talent(1310627, 5),
	Prowl:                           spelldata.Ranked(24451, 24454, 24455),
	ProwlTriggered:                  spelldata.Ranked(24450, 24452, 24453),
	RangedWeaponSpecialization:      spelldata.Talent(19507, 5),
	RapidFire:                       spelldata.Ranked(3045),
	RapidKilling:                    spelldata.Talent(415405, 2),
	RapidKillingTriggered:           spelldata.Ranked(415407),
	RapidRecuperation:               spelldata.Talent(1223987, 2),
	RapidRecuperationTriggered:      spelldata.Ranked(1242512),
	RaptorStrike:                    spelldata.Ranked(2973, 14260, 14261, 14262, 14263, 14264, 14265, 14266),
	Resourcefulness:                 spelldata.Talent(440529, 2),
	ResourcefulnessTriggered:        spelldata.Ranked(1242688),
	RevivePet:                       spelldata.Ranked(982),
	SavageRend:                      spelldata.Ranked(1265831, 1265833, 1265834, 1265835, 1265836),
	SavageRendTriggered:             spelldata.Ranked(1265065, 1265066, 1265067, 1265068, 1265069),
	SavageStrikes:                   spelldata.Talent(19159, 2),
	ScareBeast:                      spelldata.Ranked(1513, 14326, 14327),
	ScatterShot:                     spelldata.Ranked(19503),
	ScorpidPoison:                   spelldata.Ranked(24641, 24584, 24588, 24589),
	ScorpidPoisonTriggered:          spelldata.Ranked(24640, 24583, 24586, 24587),
	ScorpidSting:                    spelldata.Ranked(3043),
	SerpentSting:                    spelldata.Ranked(1978, 13549, 13550, 13551, 13552, 13553, 13554, 13555, 25295),
	ShadowResistance:                spelldata.Ranked(24490, 24514, 24515, 24516),
	ShadowResistanceTriggered:       spelldata.Ranked(24488, 24505, 24506, 24507),
	ShellShield:                     spelldata.Ranked(26065),
	ShellShieldTriggered:            spelldata.Ranked(26064),
	SlowerAttackII:                  spelldata.Ranked(1263113),
	SlowerAttackIII:                 spelldata.Ranked(1263114),
	SniperShot:                      spelldata.Ranked(1310687, 1310785, 1310786),
	SpiritBond:                      spelldata.Talent(19578, 2),
	StriderKick:                     spelldata.Ranked(1317257),
	SummonHawk:                      spelldata.Ranked(1293241, 1293525, 1293526, 1293527),
	SummonHawkTriggered:             spelldata.Ranked(1293248, 1312639),
	Surefooted:                      spelldata.Talent(19290, 3),
	SurvivalTactics:                 spelldata.Talent(19376, 2),
	Survivalist:                     spelldata.Talent(19255, 5),
	SurvivalistsDiscipline:          spelldata.Talent(1310496, 2),
	Swipe:                           spelldata.Ranked(1264727, 1264729, 1264730, 1264731, 1264732),
	SwipeTriggered:                  spelldata.Ranked(1264494, 1264497, 1264498, 1264501, 1264502),
	TameBeast:                       spelldata.Ranked(1515),
	TameBeastTriggered:              spelldata.Ranked(13535),
	TendonRip:                       spelldata.Ranked(1265043, 1265045, 1265046, 1265047, 1265048),
	TendonRipTriggered:              spelldata.Ranked(1265038, 1265039, 1265040, 1265041, 1265042),
	Thunderstomp:                    spelldata.Ranked(26094, 26189, 26190, 1264456),
	ThunderstompTriggered:           spelldata.Ranked(26090, 26187, 26188, 1264455),
	TrackBeasts:                     spelldata.Ranked(1494),
	TrackDemons:                     spelldata.Ranked(19878),
	TrackDragonkin:                  spelldata.Ranked(19879),
	TrackElementals:                 spelldata.Ranked(19880),
	TrackGiants:                     spelldata.Ranked(19882),
	TrackHidden:                     spelldata.Ranked(19885),
	TrackHumanoids:                  spelldata.Ranked(19883),
	TrackUndead:                     spelldata.Ranked(19884),
	TranquilizingShot:               spelldata.Ranked(19801),
	TrickstersDance:                 spelldata.Ranked(1310617),
	TrickstersDanceTriggered:        spelldata.Ranked(1310612),
	TrueshotAura:                    spelldata.Ranked(1299346, 1299348, 19506, 20905, 20906),
	UnleashedFury:                   spelldata.Talent(19616, 5),
	ViperSting:                      spelldata.Ranked(3034, 14279, 14280),
	Volley:                          spelldata.Ranked(1510, 14294, 14295),
	VolleyTriggered:                 spelldata.Ranked(1279721, 1279719, 1279715),
	Web:                             spelldata.Ranked(1265887, 1265888, 1265890, 1265891, 1265892),
	WebTriggered:                    spelldata.Ranked(1265843, 1265878, 1265880, 1265881, 1265883),
	WingClip:                        spelldata.Ranked(2974, 14267, 14268),
}
