// Code generated by tools/database/gen_spelldata. DO NOT EDIT.

package buffs

import (
	"time"

	"github.com/wowsims/forever/sim/core"
	"github.com/wowsims/forever/sim/core/proto"
	"github.com/wowsims/forever/sim/core/spelldata"
)

// Thunder Clap
var SynthThunderClapCategory = "AtkSpdReduction"
var synthThunderClapSpell = spelldata.MustFind(11581)
var synthThunderClapMeta = &Meta{
	Label:        "Thunder Clap",
	Spell:        synthThunderClapSpell,
	Category:     SynthThunderClapCategory,
	Talent:       spelldata.Talent(12287, 2),
	TalentEffect: 1,
}

func SynthThunderClapValue(talentPoints int32) float64 {
	return synthThunderClapMeta.Value(talentPoints)
}
func SynthThunderClapDuration(talentPoints int32) time.Duration {
	return synthThunderClapMeta.Duration(talentPoints)
}
func SynthThunderClapAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newDebuff(unit, synthThunderClapMeta, isPlayer, talentPoints)
}

// Sunder Armor
var SynthSunderArmorCategory = "MajorArmorReduction"
var synthSunderArmorSpell = spelldata.MustFind(11597)
var synthSunderArmorMeta = &Meta{
	Label:      "Sunder Armor",
	Spell:      synthSunderArmorSpell,
	Category:   SynthSunderArmorCategory,
	SingleAura: true,
}

func SynthSunderArmorValue(talentPoints int32) float64 {
	return synthSunderArmorMeta.Value(talentPoints)
}
func SynthSunderArmorDuration(talentPoints int32) time.Duration {
	return synthSunderArmorMeta.Duration(talentPoints)
}
func SynthSunderArmorAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newDebuff(unit, synthSunderArmorMeta, isPlayer, talentPoints)
}

// Expose Armor
var SynthExposeArmorCategory = "MajorArmorReduction"
var synthExposeArmorSpell = spelldata.MustFind(11198)
var synthExposeArmorMeta = &Meta{
	Label:           "Expose Armor",
	Spell:           synthExposeArmorSpell,
	Category:        SynthExposeArmorCategory,
	SingleAura:      true,
	FullComboPoints: true,
}

func SynthExposeArmorValue(talentPoints int32) float64 {
	return synthExposeArmorMeta.Value(talentPoints)
}
func SynthExposeArmorDuration(talentPoints int32) time.Duration {
	return synthExposeArmorMeta.Duration(talentPoints)
}
func SynthExposeArmorAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newDebuff(unit, synthExposeArmorMeta, isPlayer, talentPoints)
}

// Curse of the Elements
var SynthCurseOfElementsCategory = "CurseOfElements"
var synthCurseOfElementsSpell = spelldata.MustFind(1311680)
var synthCurseOfElementsMeta = &Meta{
	Label:    "Curse of the Elements",
	Spell:    synthCurseOfElementsSpell,
	Category: SynthCurseOfElementsCategory,
	PerStat:  true,
}

func SynthCurseOfElementsValue(talentPoints int32) float64 {
	return synthCurseOfElementsMeta.Value(talentPoints)
}
func SynthCurseOfElementsDuration(talentPoints int32) time.Duration {
	return synthCurseOfElementsMeta.Duration(talentPoints)
}
func SynthCurseOfElementsAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newDebuff(unit, synthCurseOfElementsMeta, isPlayer, talentPoints)
}

// Judgement of the Crusader
// func SynthJudgementOfTheCrusaderAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura // judgement_of_the_crusader: spell 20303 states no aura effect the parse attaches: effect 1 A_MOD_DAMAGE_TAKEN(14) misc 2

func applyGeneratedDebuffs(target *core.Unit, debuffs *proto.Debuffs, raid *proto.Raid) {
	if debuffs.ThunderClap {
		core.MakePermanent(SynthThunderClapAura(target, false, 0))
	}
	if debuffs.SunderArmor {
		driveSynthSunderArmor(target, debuffs, raid)
	}
	if debuffs.ExposeArmor {
		core.MakePermanent(SynthExposeArmorAura(target, false, 0))
	}
	if debuffs.CurseOfElements {
		core.MakePermanent(SynthCurseOfElementsAura(target, false, 0))
	}
}
