// Code generated by tools/database/gen_spelldata. DO NOT EDIT.

package paladin

import (
	"github.com/wowsims/forever/sim/core/spelldata"
)

// Not generated:
//   Holy Shock: ambiguous rank 2 between spells 25912, 25914; rank 3 between spells 25911, 25913; rank 4 between spells 25902, 25903
//   Judgement of Fury: missing rank 1 of 7
//   Judgement of the Crusader: missing rank 1 of 6

// Generated with an effect held at its base points, the talent tree stating no rank value for it:
//   Illumination: effect 2, 3 of spell 20210 has no rank curve and is held at its base points
//   Sacred Arbiter: effect 0 of spell 1311087 has no rank curve and is held at its base points
//   Twist of Light: effect 0 of spell 1310735 has no rank curve and is held at its base points
//   Vindication: effect 1 of spell 9452 has no rank curve and is held at its base points

type generatedSpellData struct {
	Anticipation                  spelldata.Ladder
	Benediction                   spelldata.Ladder
	BlessingOfFreedom             spelldata.Ladder
	BlessingOfKings               spelldata.Ladder
	BlessingOfLight               spelldata.Ladder
	BlessingOfMight               spelldata.Ladder
	BlessingOfProtection          spelldata.Ladder
	BlessingOfProtectionTriggered spelldata.Ladder
	BlessingOfSacrifice           spelldata.Ladder
	BlessingOfSalvation           spelldata.Ladder
	BlessingOfWisdom              spelldata.Ladder
	ChampionOfTheLight            spelldata.Ladder
	Cleanse                       spelldata.Ladder
	ConcentrationAura             spelldata.Ladder
	ConsecratedGround             spelldata.Ladder
	ConsecratedGroundTriggered    spelldata.Ladder
	Consecration                  spelldata.Ladder
	ConsecrationTriggered         spelldata.Ladder
	Conviction                    spelldata.Ladder
	Deflection                    spelldata.Ladder
	DevotionAura                  spelldata.Ladder
	DivineFavor                   spelldata.Ladder
	DivineIntellect               spelldata.Ladder
	DivineIntervention            spelldata.Ladder
	DivineInterventionTriggered   spelldata.Ladder
	DivinePrecision               spelldata.Ladder
	DivineProtection              spelldata.Ladder
	DivineProtectionTriggered     spelldata.Ladder
	DivineShield                  spelldata.Ladder
	DivineShieldTriggered         spelldata.Ladder
	DivineStrength                spelldata.Ladder
	EnhancedBlessings             spelldata.Ladder
	Exorcism                      spelldata.Ladder
	Exorcist                      spelldata.Ladder
	ExorcistTriggered             spelldata.Ladder
	EyeForAnEye                   spelldata.Ladder
	FireResistanceAura            spelldata.Ladder
	FlashOfLight                  spelldata.Ladder
	FrostResistanceAura           spelldata.Ladder
	GreaterBlessingOfKings        spelldata.Ladder
	GreaterBlessingOfLight        spelldata.Ladder
	GreaterBlessingOfMight        spelldata.Ladder
	GreaterBlessingOfSalvation    spelldata.Ladder
	GreaterBlessingOfWisdom       spelldata.Ladder
	GuardiansFavor                spelldata.Ladder
	HammerOfJustice               spelldata.Ladder
	HammerOfWrath                 spelldata.Ladder
	HammerOfTheRighteous          spelldata.Ladder
	HealingLight                  spelldata.Ladder
	HolyConduit                   spelldata.Ladder
	HolyLight                     spelldata.Ladder
	HolyPower                     spelldata.Ladder
	HolyShield                    spelldata.Ladder
	HolyStrike                    spelldata.Ladder
	HolyWrath                     spelldata.Ladder
	HolyWrathTriggered            spelldata.Ladder
	Illumination                  spelldata.Ladder
	IlluminationTriggered         spelldata.Ladder
	ImprovedBlessingOfMight       spelldata.Ladder
	ImprovedBlessingOfWisdom      spelldata.Ladder
	ImprovedFlashOfLight          spelldata.Ladder
	ImprovedHammerOfJustice       spelldata.Ladder
	ImprovedJudgement             spelldata.Ladder
	ImprovedRetributionAura       spelldata.Ladder
	ImprovedRighteousFury         spelldata.Ladder
	ImprovedSealOfFury            spelldata.Ladder
	ImprovedSealOfTheCrusader     spelldata.Ladder
	ImprovedSeals                 spelldata.Ladder
	InfusionOfLight               spelldata.Ladder
	InfusionOfLightTriggered      spelldata.Ladder
	InstrumentOfLaw               spelldata.Ladder
	IronCreed                     spelldata.Ladder
	IronCreedTriggered            spelldata.Ladder
	Judgement                     spelldata.Ladder
	JudgementOfCommand            spelldata.Ladder
	JudgementOfJustice            spelldata.Ladder
	JudgementOfLight              spelldata.Ladder
	JudgementOfLightTriggered     spelldata.Ladder
	JudgementOfRighteousness      spelldata.Ladder
	JudgementOfWisdom             spelldata.Ladder
	JudgementOfWisdomTriggered    spelldata.Ladder
	LastingJudgement              spelldata.Ladder
	LayOnHands                    spelldata.Ladder
	LightsVigil                   spelldata.Ladder
	LightsVigilTriggered          spelldata.Ladder
	OneHandedWeaponSpecialization spelldata.Ladder
	Precision                     spelldata.Ladder
	Purify                        spelldata.Ladder
	PurifyingPower                spelldata.Ladder
	PursuitOfJustice              spelldata.Ladder
	Reckoning                     spelldata.Ladder
	ReckoningTriggered            spelldata.Ladder
	Redemption                    spelldata.Ladder
	Redoubt                       spelldata.Ladder
	RedoubtTriggered              spelldata.Ladder
	Repentance                    spelldata.Ladder
	RetributionAura               spelldata.Ladder
	Reverence                     spelldata.Ladder
	RighteousFury                 spelldata.Ladder
	SacredArbiter                 spelldata.Ladder
	SacredDuty                    spelldata.Ladder
	SanctifiedJudgement           spelldata.Ladder
	SealOfCommand                 spelldata.Ladder
	SealOfCommandTriggered        spelldata.Ladder
	SealOfFury                    spelldata.Ladder
	SealOfFuryTriggered           spelldata.Ladder
	SealOfJustice                 spelldata.Ladder
	SealOfJusticeTriggered        spelldata.Ladder
	SealOfLight                   spelldata.Ladder
	SealOfLightTriggered          spelldata.Ladder
	SealOfRighteousness           spelldata.Ladder
	SealOfRighteousnessTriggered  spelldata.Ladder
	SealOfWisdom                  spelldata.Ladder
	SealOfWisdomTriggered         spelldata.Ladder
	SealOfTheCrusader             spelldata.Ladder
	SealOfTheCrusaderTriggered    spelldata.Ladder
	SenseUndead                   spelldata.Ladder
	ShadowResistanceAura          spelldata.Ladder
	ShieldSpecialization          spelldata.Ladder
	ShieldSpecializationTriggered spelldata.Ladder
	SpiritualFocus                spelldata.Ladder
	SwiftJudgement                spelldata.Ladder
	TemplarsBulwark               spelldata.Ladder
	TemplarsBulwarkTriggered      spelldata.Ladder
	Toughness                     spelldata.Ladder
	TurnUndead                    spelldata.Ladder
	TwistOfLight                  spelldata.Ladder
	TwoHandedWeaponSpecialization spelldata.Ladder
	UnyieldingFaith               spelldata.Ladder
	Vengeance                     spelldata.Ladder
	VengeanceTriggered            spelldata.Ladder
	Vindication                   spelldata.Ladder
	VindicationTriggered          spelldata.Ladder
	VoiceOfTruth                  spelldata.Ladder
}

var spellData = generatedSpellData{
	Anticipation:                  spelldata.Talent(20096, 5),
	Benediction:                   spelldata.Talent(20101, 5),
	BlessingOfFreedom:             spelldata.Ranked(1044),
	BlessingOfKings:               spelldata.Ranked(20217),
	BlessingOfLight:               spelldata.Ranked(19977, 19978, 19979),
	BlessingOfMight:               spelldata.Ranked(19740, 19834, 19835, 19836, 19837, 19838, 25291),
	BlessingOfProtection:          spelldata.Ranked(1022, 5599, 10278),
	BlessingOfProtectionTriggered: spelldata.Ranked(25771),
	BlessingOfSacrifice:           spelldata.Ranked(6940, 20729),
	BlessingOfSalvation:           spelldata.Ranked(1038),
	BlessingOfWisdom:              spelldata.Ranked(19742, 19850, 19852, 19853, 19854, 25290),
	ChampionOfTheLight:            spelldata.Talent(1311084, 3),
	Cleanse:                       spelldata.Ranked(4987),
	ConcentrationAura:             spelldata.Ranked(19746),
	ConsecratedGround:             spelldata.Talent(1310905, 2),
	ConsecratedGroundTriggered:    spelldata.Ranked(20924),
	Consecration:                  spelldata.Ranked(26573, 20116, 20922, 20923, 20924),
	ConsecrationTriggered:         spelldata.Ranked(1280345, 1280346, 1280347, 1280348, 1280349),
	Conviction:                    spelldata.Talent(20117, 5),
	Deflection:                    spelldata.Talent(20060, 5),
	DevotionAura:                  spelldata.Ranked(465, 10290, 643, 10291, 1032, 10292, 10293),
	DivineFavor:                   spelldata.Ranked(20216),
	DivineIntellect:               spelldata.Talent(20257, 5),
	DivineIntervention:            spelldata.Ranked(19752),
	DivineInterventionTriggered:   spelldata.Ranked(19753),
	DivinePrecision:               spelldata.Talent(1310904, 3),
	DivineProtection:              spelldata.Ranked(498, 5573),
	DivineProtectionTriggered:     spelldata.Ranked(25771),
	DivineShield:                  spelldata.Ranked(642, 1020),
	DivineShieldTriggered:         spelldata.Ranked(25771),
	DivineStrength:                spelldata.Talent(20262, 5),
	EnhancedBlessings:             spelldata.Ranked(435984),
	Exorcism:                      spelldata.Ranked(879, 5614, 5615, 10312, 10313, 10314),
	Exorcist:                      spelldata.Ranked(415076),
	ExorcistTriggered:             spelldata.Ranked(415068),
	EyeForAnEye:                   spelldata.Talent(9799, 2),
	FireResistanceAura:            spelldata.Ranked(19891, 19899, 19900),
	FlashOfLight:                  spelldata.Ranked(19750, 19939, 19940, 19941, 19942, 19943),
	FrostResistanceAura:           spelldata.Ranked(19888, 19897, 19898),
	GreaterBlessingOfKings:        spelldata.Ranked(25898),
	GreaterBlessingOfLight:        spelldata.Ranked(25890),
	GreaterBlessingOfMight:        spelldata.Ranked(25782, 25916),
	GreaterBlessingOfSalvation:    spelldata.Ranked(25895),
	GreaterBlessingOfWisdom:       spelldata.Ranked(25894, 25918),
	GuardiansFavor:                spelldata.Talent(20174, 2),
	HammerOfJustice:               spelldata.Ranked(853, 5588, 5589, 10308),
	HammerOfWrath:                 spelldata.Ranked(24275, 24274, 24239),
	HammerOfTheRighteous:          spelldata.Ranked(407632),
	HealingLight:                  spelldata.Talent(20237, 3),
	HolyConduit:                   spelldata.Talent(1237268, 2),
	HolyLight:                     spelldata.Ranked(635, 639, 647, 1026, 1042, 3472, 10328, 10329, 25292),
	HolyPower:                     spelldata.Talent(5923, 5),
	HolyShield:                    spelldata.Ranked(20925, 20927, 20928),
	HolyStrike:                    spelldata.Ranked(679, 678, 1866, 680, 2495, 5569, 10332, 10333),
	HolyWrath:                     spelldata.Ranked(2812, 10318),
	HolyWrathTriggered:            spelldata.Ranked(429147),
	Illumination:                  spelldata.Talent(20210, 5),
	IlluminationTriggered:         spelldata.Ranked(18350),
	ImprovedBlessingOfMight:       spelldata.Ranked(20042, 20045, 20046, 20047, 20048),
	ImprovedBlessingOfWisdom:      spelldata.Ranked(20244, 20245),
	ImprovedFlashOfLight:          spelldata.Ranked(20249, 20250, 20251),
	ImprovedHammerOfJustice:       spelldata.Talent(20487, 3),
	ImprovedJudgement:             spelldata.Talent(25956, 2),
	ImprovedRetributionAura:       spelldata.Ranked(20091, 20092),
	ImprovedRighteousFury:         spelldata.Talent(20468, 3),
	ImprovedSealOfFury:            spelldata.Ranked(1314103),
	ImprovedSealOfTheCrusader:     spelldata.Ranked(20335, 20336, 20337),
	ImprovedSeals:                 spelldata.Talent(20224, 3),
	InfusionOfLight:               spelldata.Talent(426065, 2),
	InfusionOfLightTriggered:      spelldata.Ranked(437063),
	InstrumentOfLaw:               spelldata.Talent(1311085, 2),
	IronCreed:                     spelldata.Talent(1311034, 5),
	IronCreedTriggered:            spelldata.Ranked(1311033),
	Judgement:                     spelldata.Ranked(20271),
	JudgementOfCommand:            spelldata.Ranked(20425, 20962, 20961, 20967, 20968),
	JudgementOfJustice:            spelldata.Ranked(20184),
	JudgementOfLight:              spelldata.Ranked(20185, 20344, 20345, 20346),
	JudgementOfLightTriggered:     spelldata.Ranked(5373, 20267, 20341, 20342, 20343),
	JudgementOfRighteousness:      spelldata.Ranked(20187, 20280, 20281, 20282, 20283, 20284, 20285, 20286),
	JudgementOfWisdom:             spelldata.Ranked(20186, 20354, 20355),
	JudgementOfWisdomTriggered:    spelldata.Ranked(1826, 20268, 20352, 20353),
	LastingJudgement:              spelldata.Ranked(20359, 20360, 20361),
	LayOnHands:                    spelldata.Ranked(633, 2800, 10310),
	LightsVigil:                   spelldata.Ranked(1310911, 1311590, 1311595),
	LightsVigilTriggered:          spelldata.Ranked(1310909, 1310912, 1310914, 1311591, 1311592, 1311593, 1311596, 1311597, 1311598),
	OneHandedWeaponSpecialization: spelldata.Talent(20196, 3),
	Precision:                     spelldata.Talent(20189, 3),
	Purify:                        spelldata.Ranked(1152),
	PurifyingPower:                spelldata.Talent(429144, 2),
	PursuitOfJustice:              spelldata.Talent(26022, 2),
	Reckoning:                     spelldata.Talent(20177, 5),
	ReckoningTriggered:            spelldata.Ranked(20178),
	Redemption:                    spelldata.Ranked(7328, 10322, 10324, 20772, 20773),
	Redoubt:                       spelldata.Talent(20127, 5),
	RedoubtTriggered:              spelldata.Ranked(20128),
	Repentance:                    spelldata.Ranked(20066),
	RetributionAura:               spelldata.Ranked(7294, 10298, 10299, 10300, 10301),
	Reverence:                     spelldata.Talent(1310899, 3),
	RighteousFury:                 spelldata.Ranked(25780),
	SacredArbiter:                 spelldata.Talent(1311087, 1),
	SacredDuty:                    spelldata.Talent(1224697, 2),
	SanctifiedJudgement:           spelldata.Talent(1311074, 3),
	SealOfCommand:                 spelldata.Ranked(20375, 20915, 20918, 20919, 20920),
	SealOfCommandTriggered:        spelldata.Ranked(20424, 20467, 20963, 20964, 20965, 20966),
	SealOfFury:                    spelldata.Ranked(1311649, 1311656, 20163, 20419, 20421, 20422, 20423),
	SealOfFuryTriggered:           spelldata.Ranked(20183, 20231, 20232, 20411, 20412, 20413, 20414, 20415, 20416, 20417, 20418, 1311647, 1311650, 1311654, 1311655),
	SealOfJustice:                 spelldata.Ranked(20164),
	SealOfJusticeTriggered:        spelldata.Ranked(20170, 20184),
	SealOfLight:                   spelldata.Ranked(20165, 20347, 20348, 20349),
	SealOfLightTriggered:          spelldata.Ranked(20167, 20185, 20267, 20333, 20334, 20340, 20341, 20342, 20343, 20344, 20345, 20346),
	SealOfRighteousness:           spelldata.Ranked(21084, 20287, 20288, 20289, 20290, 20291, 20292, 20293),
	SealOfRighteousnessTriggered:  spelldata.Ranked(20187, 20280, 20281, 20282, 20283, 20284, 20285, 20286),
	SealOfWisdom:                  spelldata.Ranked(20166, 20356, 20357),
	SealOfWisdomTriggered:         spelldata.Ranked(20168, 20186, 20268, 20350, 20351, 20352, 20353, 20354, 20355),
	SealOfTheCrusader:             spelldata.Ranked(21082, 20162, 20305, 20306, 20307, 20308),
	SealOfTheCrusaderTriggered:    spelldata.Ranked(21183, 20188, 20300, 20301, 20302, 20303),
	SenseUndead:                   spelldata.Ranked(5502),
	ShadowResistanceAura:          spelldata.Ranked(19876, 19895, 19896),
	ShieldSpecialization:          spelldata.Talent(20150, 3),
	ShieldSpecializationTriggered: spelldata.Ranked(1310925),
	SpiritualFocus:                spelldata.Talent(20205, 2),
	SwiftJudgement:                spelldata.Ranked(1310994),
	TemplarsBulwark:               spelldata.Ranked(1311015),
	TemplarsBulwarkTriggered:      spelldata.Ranked(25771),
	Toughness:                     spelldata.Talent(20143, 5),
	TurnUndead:                    spelldata.Ranked(2878, 5627, 10326),
	TwistOfLight:                  spelldata.Talent(1310735, 1),
	TwoHandedWeaponSpecialization: spelldata.Talent(20111, 3),
	UnyieldingFaith:               spelldata.Talent(9453, 2),
	Vengeance:                     spelldata.Talent(20049, 3),
	VengeanceTriggered:            spelldata.Ranked(20050),
	Vindication:                   spelldata.Talent(9452, 3),
	VindicationTriggered:          spelldata.Ranked(440667),
	VoiceOfTruth:                  spelldata.Ranked(1310897),
}
