// Code generated by tools/database/gen_spelldata. DO NOT EDIT.

package buffs

import (
	"time"

	"github.com/wowsims/forever/sim/core"
	"github.com/wowsims/forever/sim/core/dbcenums"
	"github.com/wowsims/forever/sim/core/proto"
	"github.com/wowsims/forever/sim/core/spelldata"
)

// The category the rows that name it join without an effect of their own, so
// that a player's own copy of one of them shuts the others off.
var PaladinAuraCategory = "PaladinAura"

// Blood Pact
var bloodPactSpell = spelldata.MustFind(11767)
var bloodPactMeta = &Meta{
	Label: "Blood Pact",
	Spell: bloodPactSpell,
}

func BloodPactValue(talentPoints int32) float64 {
	return bloodPactMeta.Value(talentPoints)
}
func BloodPactDuration(talentPoints int32) time.Duration {
	return bloodPactMeta.Duration(talentPoints)
}
func BloodPactAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newBuff(unit, bloodPactMeta, isPlayer, talentPoints)
}

// Battle Shout
var BattleShoutCategory = "BattleShout"
var battleShoutSpell = spelldata.MustFind(25289)
var battleShoutMeta = &Meta{
	Label:      "Battle Shout",
	Spell:      battleShoutSpell,
	Category:   BattleShoutCategory,
	SingleAura: true,
}

func BattleShoutValue(talentPoints int32) float64 {
	return battleShoutMeta.Value(talentPoints)
}
func BattleShoutDuration(talentPoints int32) time.Duration {
	return battleShoutMeta.Duration(talentPoints)
}
func BattleShoutAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newBuff(unit, battleShoutMeta, isPlayer, talentPoints)
}

// Devotion Aura
var DevotionAuraCategory = "DevotionAura"
var devotionAuraSpell = spelldata.MustFind(10293)
var devotionAuraMeta = &Meta{
	Label:          "Devotion Aura",
	Spell:          devotionAuraSpell,
	Category:       DevotionAuraCategory,
	SharedCategory: PaladinAuraCategory,
	SingleAura:     true,
	SkipAuras:      []dbcenums.EffectAuraType{dbcenums.A_MOD_HEALING_PCT},
}

func DevotionAuraValue(talentPoints int32) float64 {
	return devotionAuraMeta.Value(talentPoints)
}
func DevotionAuraDuration(talentPoints int32) time.Duration {
	return devotionAuraMeta.Duration(talentPoints)
}
func DevotionAuraAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newBuff(unit, devotionAuraMeta, isPlayer, talentPoints)
}

// Leader of the Pack
var LeaderOfThePackCategory = "DruidCritAura"
var leaderOfThePackSpell = spelldata.MustFind(24932)
var leaderOfThePackMeta = &Meta{
	Label:      "Leader of the Pack",
	Spell:      leaderOfThePackSpell,
	Category:   LeaderOfThePackCategory,
	SingleAura: true,
}

func LeaderOfThePackValue(talentPoints int32) float64 {
	return leaderOfThePackMeta.Value(talentPoints)
}
func LeaderOfThePackDuration(talentPoints int32) time.Duration {
	return leaderOfThePackMeta.Duration(talentPoints)
}
func LeaderOfThePackAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newBuff(unit, leaderOfThePackMeta, isPlayer, talentPoints)
}

// Mana Spring Totem
var ManaSpringTotemCategory = "ManaSpringTotem"
var manaSpringTotemSpell = spelldata.MustFind(10494)
var manaSpringTotemMeta = &Meta{
	Label:        "Mana Spring Totem",
	Spell:        manaSpringTotemSpell,
	Category:     ManaSpringTotemCategory,
	Talent:       spelldata.Talent(16187, 5),
	TalentEffect: 1,
}

func ManaSpringTotemValue(talentPoints int32) float64 {
	return manaSpringTotemMeta.Value(talentPoints)
}
func ManaSpringTotemDuration(talentPoints int32) time.Duration {
	return manaSpringTotemMeta.Duration(talentPoints)
}
func ManaSpringTotemAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newBuff(unit, manaSpringTotemMeta, isPlayer, talentPoints)
}

// Mana Tide Totem
var ManaTideTotemsCategory = "ManaTideTotem"
var manaTideTotemsSpell = spelldata.MustFind(17360)
var manaTideTotemsMeta = &Meta{
	Label:    "Mana Tide Totem",
	Spell:    manaTideTotemsSpell,
	Cast:     spelldata.MustFind(17359),
	Category: ManaTideTotemsCategory,
}

func ManaTideTotemsValue(talentPoints int32) float64 {
	return manaTideTotemsMeta.Value(talentPoints)
}
func ManaTideTotemsDuration(talentPoints int32) time.Duration {
	return manaTideTotemsMeta.Duration(talentPoints)
}
func ManaTideTotemsCooldown() time.Duration {
	return manaTideTotemsMeta.Cooldown()
}
func ManaTideTotemsAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newBuff(unit, manaTideTotemsMeta, isPlayer, talentPoints)
}

// Moonkin Aura
var MoonkinAuraCategory = "DruidCritAura"
var moonkinAuraSpell = spelldata.MustFind(24907)
var moonkinAuraMeta = &Meta{
	Label:      "Moonkin Aura",
	Spell:      moonkinAuraSpell,
	Category:   MoonkinAuraCategory,
	SingleAura: true,
}

func MoonkinAuraValue(talentPoints int32) float64 {
	return moonkinAuraMeta.Value(talentPoints)
}
func MoonkinAuraDuration(talentPoints int32) time.Duration {
	return moonkinAuraMeta.Duration(talentPoints)
}
func MoonkinAuraAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newBuff(unit, moonkinAuraMeta, isPlayer, talentPoints)
}

// Retribution Aura
var RetributionAuraCategory = "RetributionAura"
var retributionAuraSpell = spelldata.MustFind(10301)
var retributionAuraMeta = &Meta{
	Label:          "Retribution Aura",
	Spell:          retributionAuraSpell,
	Category:       RetributionAuraCategory,
	SharedCategory: PaladinAuraCategory,
	SingleAura:     true,
	SkipAuras:      []dbcenums.EffectAuraType{dbcenums.A_MOD_HEALING_PCT},
}

func RetributionAuraValue(talentPoints int32) float64 {
	return retributionAuraMeta.Value(talentPoints)
}
func RetributionAuraDuration(talentPoints int32) time.Duration {
	return retributionAuraMeta.Duration(talentPoints)
}
func RetributionAuraAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newDamageShield(unit, retributionAuraMeta, isPlayer, talentPoints)
}

// func RetributionAuraSpellPowerAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura // retribution_aura_spell_power, KindFlag: retired: Retribution Aura reads the spell power of the unit it is on, not the paladin's (beta logs 2729-2736), so nothing reads this; the row stays so the party fields after it keep their proto numbers.

// Concentration Aura
// Left out: effect 3 A_MECHANIC_DURATION_MOD(232) misc 26
// Left out: effect 4 A_MECHANIC_DURATION_MOD(232) misc 9
var ConcentrationAuraCategory = "ConcentrationAura"
var concentrationAuraSpell = spelldata.MustFind(19746)
var concentrationAuraMeta = &Meta{
	Label:          "Concentration Aura",
	Spell:          concentrationAuraSpell,
	Category:       ConcentrationAuraCategory,
	SharedCategory: PaladinAuraCategory,
	SingleAura:     true,
	SkipAuras:      []dbcenums.EffectAuraType{dbcenums.A_MOD_HEALING_PCT},
}

func ConcentrationAuraValue(talentPoints int32) float64 {
	return concentrationAuraMeta.Value(talentPoints)
}
func ConcentrationAuraDuration(talentPoints int32) time.Duration {
	return concentrationAuraMeta.Duration(talentPoints)
}
func ConcentrationAuraAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newBuff(unit, concentrationAuraMeta, isPlayer, talentPoints)
}

// Trueshot Aura
var trueshotAuraSpell = spelldata.MustFind(20905)
var trueshotAuraMeta = &Meta{
	Label: "Trueshot Aura",
	Spell: trueshotAuraSpell,
}

func TrueshotAuraValue(talentPoints int32) float64 {
	return trueshotAuraMeta.Value(talentPoints)
}
func TrueshotAuraDuration(talentPoints int32) time.Duration {
	return trueshotAuraMeta.Duration(talentPoints)
}
func TrueshotAuraAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newBuff(unit, trueshotAuraMeta, isPlayer, talentPoints)
}

// Atiesh - Mage
var atieshMageSpell = spelldata.MustFind(28142)
var atieshMageMeta = &Meta{
	Label: "Atiesh - Mage",
	Spell: atieshMageSpell,
}

func AtieshMageValue(talentPoints int32) float64 {
	return atieshMageMeta.Value(talentPoints)
}
func AtieshMageDuration(talentPoints int32) time.Duration {
	return atieshMageMeta.Duration(talentPoints)
}
func AtieshMageAura(unit *core.Unit, isPlayer bool, talentPoints int32, count float64) *core.Aura {
	return newItemCountBuff(unit, atieshMageMeta, isPlayer, count)
}

// Atiesh - Warlock
var atieshWarlockSpell = spelldata.MustFind(28143)
var atieshWarlockMeta = &Meta{
	Label: "Atiesh - Warlock",
	Spell: atieshWarlockSpell,
}

func AtieshWarlockValue(talentPoints int32) float64 {
	return atieshWarlockMeta.Value(talentPoints)
}
func AtieshWarlockDuration(talentPoints int32) time.Duration {
	return atieshWarlockMeta.Duration(talentPoints)
}
func AtieshWarlockAura(unit *core.Unit, isPlayer bool, talentPoints int32, count float64) *core.Aura {
	return newItemCountBuff(unit, atieshWarlockMeta, isPlayer, count)
}

// Strength of Earth Totem
var StrengthOfEarthTotemCategory = "StrengthOfEarthTotem"
var strengthOfEarthTotemSpell = spelldata.MustFind(25362)
var strengthOfEarthTotemMeta = &Meta{
	Label:    "Strength of Earth Totem",
	Spell:    strengthOfEarthTotemSpell,
	Category: StrengthOfEarthTotemCategory,
}

func StrengthOfEarthTotemValue(talentPoints int32) float64 {
	return strengthOfEarthTotemMeta.Value(talentPoints)
}
func StrengthOfEarthTotemDuration(talentPoints int32) time.Duration {
	return strengthOfEarthTotemMeta.Duration(talentPoints)
}
func StrengthOfEarthTotemAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newBuff(unit, strengthOfEarthTotemMeta, isPlayer, talentPoints)
}

// Grace of Air Totem
var GraceOfAirTotemCategory = "GraceOfAirTotem"
var graceOfAirTotemSpell = spelldata.MustFind(25360)
var graceOfAirTotemMeta = &Meta{
	Label:    "Grace of Air Totem",
	Spell:    graceOfAirTotemSpell,
	Category: GraceOfAirTotemCategory,
}

func GraceOfAirTotemValue(talentPoints int32) float64 {
	return graceOfAirTotemMeta.Value(talentPoints)
}
func GraceOfAirTotemDuration(talentPoints int32) time.Duration {
	return graceOfAirTotemMeta.Duration(talentPoints)
}
func GraceOfAirTotemAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newBuff(unit, graceOfAirTotemMeta, isPlayer, talentPoints)
}

// Windfury Totem
var WindfuryTotemCategory = "WindfuryTotem"
var windfuryTotemSpell = spelldata.MustFind(10610)
var windfuryTotemMeta = &Meta{
	Label:    "Windfury Totem",
	Spell:    windfuryTotemSpell,
	Category: WindfuryTotemCategory,
}

func WindfuryTotemValue(talentPoints int32) float64 {
	return windfuryTotemMeta.Value(talentPoints)
}
func WindfuryTotemDuration(talentPoints int32) time.Duration {
	return windfuryTotemMeta.Duration(talentPoints)
}
func WindfuryTotemAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newBuff(unit, windfuryTotemMeta, isPlayer, talentPoints)
}

// Atiesh - Druid
var atieshDruidSpell = spelldata.MustFind(28145)
var atieshDruidMeta = &Meta{
	Label: "Atiesh - Druid",
	Spell: atieshDruidSpell,
}

func AtieshDruidValue(talentPoints int32) float64 {
	return atieshDruidMeta.Value(talentPoints)
}
func AtieshDruidDuration(talentPoints int32) time.Duration {
	return atieshDruidMeta.Duration(talentPoints)
}
func AtieshDruidAura(unit *core.Unit, isPlayer bool, talentPoints int32, count float64) *core.Aura {
	return newItemCountBuff(unit, atieshDruidMeta, isPlayer, count)
}

// Atiesh - Priest
var atieshPriestSpell = spelldata.MustFind(28144)
var atieshPriestMeta = &Meta{
	Label: "Atiesh - Priest",
	Spell: atieshPriestSpell,
}

func AtieshPriestValue(talentPoints int32) float64 {
	return atieshPriestMeta.Value(talentPoints)
}
func AtieshPriestDuration(talentPoints int32) time.Duration {
	return atieshPriestMeta.Duration(talentPoints)
}
func AtieshPriestAura(unit *core.Unit, isPlayer bool, talentPoints int32, count float64) *core.Aura {
	return newItemCountBuff(unit, atieshPriestMeta, isPlayer, count)
}

// func TotemTwistingAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura // totem_twisting, KindFlag: sim behaviour toggle with no spell source; rendered under Other Inputs.

// Flametongue Totem
// Left out: effect 1 A_PROC_TRIGGER_SPELL(42) misc 0
var FlametongueTotemCategory = "FlametongueTotem"
var flametongueTotemSpell = spelldata.MustFind(15036)
var flametongueTotemMeta = &Meta{
	Label:    "Flametongue Totem",
	Spell:    flametongueTotemSpell,
	Category: FlametongueTotemCategory,
}

func FlametongueTotemDuration(talentPoints int32) time.Duration {
	return flametongueTotemMeta.Duration(talentPoints)
}
func FlametongueTotemAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newBuff(unit, flametongueTotemMeta, isPlayer, talentPoints)
}

// Arcane Brilliance
var ArcaneBrillianceCategory = "StatBuff"
var arcaneBrillianceSpell = spelldata.MustFind(23028)
var arcaneBrillianceMeta = &Meta{
	Label:    "Arcane Brilliance",
	Spell:    arcaneBrillianceSpell,
	Category: ArcaneBrillianceCategory,
}

func ArcaneBrillianceValue(talentPoints int32) float64 {
	return arcaneBrillianceMeta.Value(talentPoints)
}
func ArcaneBrillianceDuration(talentPoints int32) time.Duration {
	return arcaneBrillianceMeta.Duration(talentPoints)
}
func ArcaneBrillianceAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newBuff(unit, arcaneBrillianceMeta, isPlayer, talentPoints)
}

// Prayer of Spirit
var PrayerOfSpiritCategory = "StatBuff"
var prayerOfSpiritSpell = spelldata.MustFind(27681)
var prayerOfSpiritMeta = &Meta{
	Label:    "Prayer of Spirit",
	Spell:    prayerOfSpiritSpell,
	Category: PrayerOfSpiritCategory,
}

func PrayerOfSpiritValue(talentPoints int32) float64 {
	return prayerOfSpiritMeta.Value(talentPoints)
}
func PrayerOfSpiritDuration(talentPoints int32) time.Duration {
	return prayerOfSpiritMeta.Duration(talentPoints)
}
func PrayerOfSpiritAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newBuff(unit, prayerOfSpiritMeta, isPlayer, talentPoints)
}

// Gift of the Wild
// Left out: effect 3 A_MOD_RESISTANCE(22) misc 2
var giftOfTheWildSpell = spelldata.MustFind(21850)
var giftOfTheWildMeta = &Meta{
	Label: "Gift of the Wild",
	Spell: giftOfTheWildSpell,
}

func GiftOfTheWildValue(talentPoints int32) float64 {
	return giftOfTheWildMeta.Value(talentPoints)
}
func GiftOfTheWildDuration(talentPoints int32) time.Duration {
	return giftOfTheWildMeta.Duration(talentPoints)
}
func GiftOfTheWildAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newBuff(unit, giftOfTheWildMeta, isPlayer, talentPoints)
}

// Thorns
var ThornsCategory = "Thorns"
var thornsSpell = spelldata.MustFind(9910)
var thornsMeta = &Meta{
	Label:      "Thorns",
	Spell:      thornsSpell,
	Category:   ThornsCategory,
	SingleAura: true,
}

func ThornsValue(talentPoints int32) float64 {
	return thornsMeta.Value(talentPoints)
}
func ThornsDuration(talentPoints int32) time.Duration {
	return thornsMeta.Duration(talentPoints)
}
func ThornsAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newDamageShield(unit, thornsMeta, isPlayer, talentPoints)
}

// Prayer of Fortitude
var prayerOfFortitudeSpell = spelldata.MustFind(21564)
var prayerOfFortitudeMeta = &Meta{
	Label: "Prayer of Fortitude",
	Spell: prayerOfFortitudeSpell,
}

func PrayerOfFortitudeValue(talentPoints int32) float64 {
	return prayerOfFortitudeMeta.Value(talentPoints)
}
func PrayerOfFortitudeDuration(talentPoints int32) time.Duration {
	return prayerOfFortitudeMeta.Duration(talentPoints)
}
func PrayerOfFortitudeAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newBuff(unit, prayerOfFortitudeMeta, isPlayer, talentPoints)
}

// Prayer of Shadow Protection
var prayerOfShadowProtectionSpell = spelldata.MustFind(27683)
var prayerOfShadowProtectionMeta = &Meta{
	Label: "Prayer of Shadow Protection",
	Spell: prayerOfShadowProtectionSpell,
}

func PrayerOfShadowProtectionValue(talentPoints int32) float64 {
	return prayerOfShadowProtectionMeta.Value(talentPoints)
}
func PrayerOfShadowProtectionDuration(talentPoints int32) time.Duration {
	return prayerOfShadowProtectionMeta.Duration(talentPoints)
}
func PrayerOfShadowProtectionAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newBuff(unit, prayerOfShadowProtectionMeta, isPlayer, talentPoints)
}

// Fire Resistance Aura
var FireResistanceAuraCategory = "FireResistanceAura"
var fireResistanceAuraSpell = spelldata.MustFind(19900)
var fireResistanceAuraMeta = &Meta{
	Label:          "Fire Resistance Aura",
	Spell:          fireResistanceAuraSpell,
	Category:       FireResistanceAuraCategory,
	SharedCategory: PaladinAuraCategory,
	SingleAura:     true,
	SkipAuras:      []dbcenums.EffectAuraType{dbcenums.A_MOD_HEALING_PCT},
}

func FireResistanceAuraValue(talentPoints int32) float64 {
	return fireResistanceAuraMeta.Value(talentPoints)
}
func FireResistanceAuraDuration(talentPoints int32) time.Duration {
	return fireResistanceAuraMeta.Duration(talentPoints)
}
func FireResistanceAuraAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newBuff(unit, fireResistanceAuraMeta, isPlayer, talentPoints)
}

// Frost Resistance Aura
var FrostResistanceAuraCategory = "FrostResistanceAura"
var frostResistanceAuraSpell = spelldata.MustFind(19898)
var frostResistanceAuraMeta = &Meta{
	Label:          "Frost Resistance Aura",
	Spell:          frostResistanceAuraSpell,
	Category:       FrostResistanceAuraCategory,
	SharedCategory: PaladinAuraCategory,
	SingleAura:     true,
	SkipAuras:      []dbcenums.EffectAuraType{dbcenums.A_MOD_HEALING_PCT},
}

func FrostResistanceAuraValue(talentPoints int32) float64 {
	return frostResistanceAuraMeta.Value(talentPoints)
}
func FrostResistanceAuraDuration(talentPoints int32) time.Duration {
	return frostResistanceAuraMeta.Duration(talentPoints)
}
func FrostResistanceAuraAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newBuff(unit, frostResistanceAuraMeta, isPlayer, talentPoints)
}

// Shadow Resistance Aura
var ShadowResistanceAuraCategory = "ShadowResistanceAura"
var shadowResistanceAuraSpell = spelldata.MustFind(19896)
var shadowResistanceAuraMeta = &Meta{
	Label:          "Shadow Resistance Aura",
	Spell:          shadowResistanceAuraSpell,
	Category:       ShadowResistanceAuraCategory,
	SharedCategory: PaladinAuraCategory,
	SingleAura:     true,
	SkipAuras:      []dbcenums.EffectAuraType{dbcenums.A_MOD_HEALING_PCT},
}

func ShadowResistanceAuraValue(talentPoints int32) float64 {
	return shadowResistanceAuraMeta.Value(talentPoints)
}
func ShadowResistanceAuraDuration(talentPoints int32) time.Duration {
	return shadowResistanceAuraMeta.Duration(talentPoints)
}
func ShadowResistanceAuraAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newBuff(unit, shadowResistanceAuraMeta, isPlayer, talentPoints)
}

// Fire Resistance Totem
var fireResistanceTotemSpell = spelldata.MustFind(10535)
var fireResistanceTotemMeta = &Meta{
	Label: "Fire Resistance Totem",
	Spell: fireResistanceTotemSpell,
}

func FireResistanceTotemValue(talentPoints int32) float64 {
	return fireResistanceTotemMeta.Value(talentPoints)
}
func FireResistanceTotemDuration(talentPoints int32) time.Duration {
	return fireResistanceTotemMeta.Duration(talentPoints)
}
func FireResistanceTotemAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newBuff(unit, fireResistanceTotemMeta, isPlayer, talentPoints)
}

// Frost Resistance Totem
var frostResistanceTotemSpell = spelldata.MustFind(10477)
var frostResistanceTotemMeta = &Meta{
	Label: "Frost Resistance Totem",
	Spell: frostResistanceTotemSpell,
}

func FrostResistanceTotemValue(talentPoints int32) float64 {
	return frostResistanceTotemMeta.Value(talentPoints)
}
func FrostResistanceTotemDuration(talentPoints int32) time.Duration {
	return frostResistanceTotemMeta.Duration(talentPoints)
}
func FrostResistanceTotemAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newBuff(unit, frostResistanceTotemMeta, isPlayer, talentPoints)
}

// Nature Resistance Totem
var natureResistanceTotemSpell = spelldata.MustFind(10599)
var natureResistanceTotemMeta = &Meta{
	Label: "Nature Resistance Totem",
	Spell: natureResistanceTotemSpell,
}

func NatureResistanceTotemValue(talentPoints int32) float64 {
	return natureResistanceTotemMeta.Value(talentPoints)
}
func NatureResistanceTotemDuration(talentPoints int32) time.Duration {
	return natureResistanceTotemMeta.Duration(talentPoints)
}
func NatureResistanceTotemAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newBuff(unit, natureResistanceTotemMeta, isPlayer, talentPoints)
}

// Aspect of the Wild
var aspectOfTheWildSpell = spelldata.MustFind(20190)
var aspectOfTheWildMeta = &Meta{
	Label: "Aspect of the Wild",
	Spell: aspectOfTheWildSpell,
}

func AspectOfTheWildValue(talentPoints int32) float64 {
	return aspectOfTheWildMeta.Value(talentPoints)
}
func AspectOfTheWildDuration(talentPoints int32) time.Duration {
	return aspectOfTheWildMeta.Duration(talentPoints)
}
func AspectOfTheWildAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newBuff(unit, aspectOfTheWildMeta, isPlayer, talentPoints)
}

// Greater Blessing of Kings
var greaterBlessingOfKingsSpell = spelldata.MustFind(25898)
var greaterBlessingOfKingsMeta = &Meta{
	Label: "Greater Blessing of Kings",
	Spell: greaterBlessingOfKingsSpell,
}

func GreaterBlessingOfKingsValue(talentPoints int32) float64 {
	return greaterBlessingOfKingsMeta.Value(talentPoints)
}
func GreaterBlessingOfKingsDuration(talentPoints int32) time.Duration {
	return greaterBlessingOfKingsMeta.Duration(talentPoints)
}
func GreaterBlessingOfKingsAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newBuff(unit, greaterBlessingOfKingsMeta, isPlayer, talentPoints)
}

// Greater Blessing of Might
var greaterBlessingOfMightSpell = spelldata.MustFind(25916)
var greaterBlessingOfMightMeta = &Meta{
	Label: "Greater Blessing of Might",
	Spell: greaterBlessingOfMightSpell,
}

func GreaterBlessingOfMightValue(talentPoints int32) float64 {
	return greaterBlessingOfMightMeta.Value(talentPoints)
}
func GreaterBlessingOfMightDuration(talentPoints int32) time.Duration {
	return greaterBlessingOfMightMeta.Duration(talentPoints)
}
func GreaterBlessingOfMightAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newBuff(unit, greaterBlessingOfMightMeta, isPlayer, talentPoints)
}

// Greater Blessing of Wisdom
var greaterBlessingOfWisdomSpell = spelldata.MustFind(25918)
var greaterBlessingOfWisdomMeta = &Meta{
	Label: "Greater Blessing of Wisdom",
	Spell: greaterBlessingOfWisdomSpell,
}

func GreaterBlessingOfWisdomValue(talentPoints int32) float64 {
	return greaterBlessingOfWisdomMeta.Value(talentPoints)
}
func GreaterBlessingOfWisdomDuration(talentPoints int32) time.Duration {
	return greaterBlessingOfWisdomMeta.Duration(talentPoints)
}
func GreaterBlessingOfWisdomAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newBuff(unit, greaterBlessingOfWisdomMeta, isPlayer, talentPoints)
}

// Greater Blessing of Salvation
var greaterBlessingOfSalvationSpell = spelldata.MustFind(25895)
var greaterBlessingOfSalvationMeta = &Meta{
	Label: "Greater Blessing of Salvation",
	Spell: greaterBlessingOfSalvationSpell,
}

func GreaterBlessingOfSalvationValue(talentPoints int32) float64 {
	return greaterBlessingOfSalvationMeta.Value(talentPoints)
}
func GreaterBlessingOfSalvationDuration(talentPoints int32) time.Duration {
	return greaterBlessingOfSalvationMeta.Duration(talentPoints)
}
func GreaterBlessingOfSalvationAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newBuff(unit, greaterBlessingOfSalvationMeta, isPlayer, talentPoints)
}

// Greater Blessing of Light
// Left out: effect 1 A_DUMMY(4) misc 0
// Left out: effect 2 A_DUMMY(4) misc 0
var GreaterBlessingOfLightCategory = "BlessingOfLight"
var greaterBlessingOfLightSpell = spelldata.MustFind(25890)
var greaterBlessingOfLightMeta = &Meta{
	Label:    "Greater Blessing of Light",
	Spell:    greaterBlessingOfLightSpell,
	Category: GreaterBlessingOfLightCategory,
}

func GreaterBlessingOfLightDuration(talentPoints int32) time.Duration {
	return greaterBlessingOfLightMeta.Duration(talentPoints)
}
func GreaterBlessingOfLightAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newBuff(unit, greaterBlessingOfLightMeta, isPlayer, talentPoints)
}

// Innervates
// Left out: effect 1 A_MOD_MANA_REGEN_INTERRUPT(134) misc 0
// Left out: effect 2 A_MOD_POWER_REGEN_PERCENT(110) misc 0
var InnervatesCategory = "Innervate"
var innervatesSpell = spelldata.MustFind(29166)
var innervatesMeta = &Meta{
	Label:    "Innervates",
	Spell:    innervatesSpell,
	Category: InnervatesCategory,
}

func InnervatesDuration(talentPoints int32) time.Duration {
	return innervatesMeta.Duration(talentPoints)
}
func InnervatesCooldown() time.Duration {
	return innervatesMeta.Cooldown()
}
func InnervatesAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newBuff(unit, innervatesMeta, isPlayer, talentPoints)
}

// Power Infusions
var PowerInfusionsCategory = "PowerInfusion"
var powerInfusionsSpell = spelldata.MustFind(10060)
var powerInfusionsMeta = &Meta{
	Label:    "Power Infusions",
	Spell:    powerInfusionsSpell,
	Category: PowerInfusionsCategory,
}

func PowerInfusionsValue(talentPoints int32) float64 {
	return powerInfusionsMeta.Value(talentPoints)
}
func PowerInfusionsDuration(talentPoints int32) time.Duration {
	return powerInfusionsMeta.Duration(talentPoints)
}
func PowerInfusionsCooldown() time.Duration {
	return powerInfusionsMeta.Cooldown()
}
func PowerInfusionsAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newBuff(unit, powerInfusionsMeta, isPlayer, talentPoints)
}

func applyGeneratedBuffs(char *core.Character, raid *proto.RaidBuffs, party *proto.PartyBuffs, individual *proto.IndividualBuffs) {
	if party.BloodPact {
		core.MakePermanent(BloodPactAura(&char.Unit, false, 0))
	}
	if party.BattleShout != proto.TristateEffect_TristateEffectMissing {
		driveBattleShout(char, party)
	}
	if party.DevotionAura {
		core.MakePermanent(DevotionAuraAura(&char.Unit, false, 0))
	}
	if party.LeaderOfThePack {
		core.MakePermanent(LeaderOfThePackAura(&char.Unit, false, 0))
	}
	if party.ManaSpringTotem != proto.TristateEffect_TristateEffectMissing {
		core.MakePermanent(ManaSpringTotemAura(&char.Unit, false, core.GetTristateValueInt32(party.ManaSpringTotem, 0, 5)))
	}
	if party.ManaTideTotems > 0 {
		driveManaTideTotems(char, party)
	}
	if party.MoonkinAura {
		core.MakePermanent(MoonkinAuraAura(&char.Unit, false, 0))
	}
	if party.RetributionAura {
		driveRetributionAura(char, party)
	}
	if party.ConcentrationAura {
		core.MakePermanent(ConcentrationAuraAura(&char.Unit, false, 0))
	}
	if party.TrueshotAura {
		core.MakePermanent(TrueshotAuraAura(&char.Unit, false, 0))
	}
	if party.AtieshMage > 0 {
		driveAtieshMage(char, party)
	}
	if party.AtieshWarlock > 0 {
		driveAtieshWarlock(char, party)
	}
	if party.StrengthOfEarthTotem {
		core.MakePermanent(StrengthOfEarthTotemAura(&char.Unit, false, 0))
	}
	if party.GraceOfAirTotem {
		driveGraceOfAirTotem(char, party)
	}
	if party.WindfuryTotem {
		driveWindfuryTotem(char, party)
	}
	if party.AtieshDruid > 0 {
		driveAtieshDruid(char, party)
	}
	if party.AtieshPriest > 0 {
		driveAtieshPriest(char, party)
	}
	if party.FlametongueTotem {
		driveFlametongueTotem(char, party)
	}
	if raid.ArcaneBrilliance {
		core.MakePermanent(ArcaneBrillianceAura(&char.Unit, false, 0))
	}
	if raid.PrayerOfSpirit {
		core.MakePermanent(PrayerOfSpiritAura(&char.Unit, false, 0))
	}
	if raid.GiftOfTheWild {
		core.MakePermanent(GiftOfTheWildAura(&char.Unit, false, 0))
	}
	if raid.Thorns {
		core.MakePermanent(ThornsAura(&char.Unit, false, 0))
	}
	if raid.PrayerOfFortitude {
		core.MakePermanent(PrayerOfFortitudeAura(&char.Unit, false, 0))
	}
	if raid.PrayerOfShadowProtection {
		core.MakePermanent(PrayerOfShadowProtectionAura(&char.Unit, false, 0))
	}
	if raid.FireResistanceAura {
		core.MakePermanent(FireResistanceAuraAura(&char.Unit, false, 0))
	}
	if raid.FrostResistanceAura {
		core.MakePermanent(FrostResistanceAuraAura(&char.Unit, false, 0))
	}
	if raid.ShadowResistanceAura {
		core.MakePermanent(ShadowResistanceAuraAura(&char.Unit, false, 0))
	}
	if raid.FireResistanceTotem {
		core.MakePermanent(FireResistanceTotemAura(&char.Unit, false, 0))
	}
	if raid.FrostResistanceTotem {
		core.MakePermanent(FrostResistanceTotemAura(&char.Unit, false, 0))
	}
	if raid.NatureResistanceTotem {
		core.MakePermanent(NatureResistanceTotemAura(&char.Unit, false, 0))
	}
	if raid.AspectOfTheWild {
		core.MakePermanent(AspectOfTheWildAura(&char.Unit, false, 0))
	}
	if individual.GreaterBlessingOfKings {
		core.MakePermanent(GreaterBlessingOfKingsAura(&char.Unit, false, 0))
	}
	if individual.GreaterBlessingOfMight {
		core.MakePermanent(GreaterBlessingOfMightAura(&char.Unit, false, 0))
	}
	if individual.GreaterBlessingOfWisdom {
		core.MakePermanent(GreaterBlessingOfWisdomAura(&char.Unit, false, 0))
	}
	if individual.GreaterBlessingOfSalvation {
		core.MakePermanent(GreaterBlessingOfSalvationAura(&char.Unit, false, 0))
	}
	if individual.GreaterBlessingOfLight {
		driveGreaterBlessingOfLight(char, individual)
	}
	if individual.Innervates > 0 {
		driveInnervates(char, individual)
	}
	if individual.PowerInfusions > 0 {
		drivePowerInfusions(char, individual)
	}
}
