// Code generated by tools/database/gen_spelldata. DO NOT EDIT.

package buffs

import (
	"time"

	"github.com/wowsims/forever/sim/core"
	"github.com/wowsims/forever/sim/core/proto"
	"github.com/wowsims/forever/sim/core/spelldata"
)

// Hunter's Mark
// Left out: effect 1 A_MOD_STALKED(68) misc 0
var HuntersMarkCategory = "HuntersMark"
var huntersMarkSpell = spelldata.MustFind(14325)
var huntersMarkMeta = &Meta{
	Label:      "Hunter's Mark",
	Spell:      huntersMarkSpell,
	Category:   HuntersMarkCategory,
	SingleAura: true,
}

func HuntersMarkValue(talentPoints int32) float64 {
	return huntersMarkMeta.Value(talentPoints)
}
func HuntersMarkDuration(talentPoints int32) time.Duration {
	return huntersMarkMeta.Duration(talentPoints)
}
func HuntersMarkAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newDebuff(unit, huntersMarkMeta, isPlayer, talentPoints)
}

// Judgement of the Crusader
// func JudgementOfTheCrusaderAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura // judgement_of_the_crusader: spell 20303 states no aura effect the parse attaches: effect 1 A_MOD_DAMAGE_TAKEN(14) misc 2

// Judgement of Light
// Left out: effect 1 A_PROC_TRIGGER_SPELL(42) misc 0
var judgementOfLightSpell = spelldata.MustFind(20346)
var judgementOfLightMeta = &Meta{
	Label: "Judgement of Light",
	Spell: judgementOfLightSpell,
}

func JudgementOfLightDuration(talentPoints int32) time.Duration {
	return judgementOfLightMeta.Duration(talentPoints)
}
func JudgementOfLightAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newDebuff(unit, judgementOfLightMeta, isPlayer, talentPoints)
}

// Judgement of Wisdom
// Left out: effect 1 A_PROC_TRIGGER_SPELL(42) misc 0
var judgementOfWisdomSpell = spelldata.MustFind(20355)
var judgementOfWisdomMeta = &Meta{
	Label: "Judgement of Wisdom",
	Spell: judgementOfWisdomSpell,
}

func JudgementOfWisdomDuration(talentPoints int32) time.Duration {
	return judgementOfWisdomMeta.Duration(talentPoints)
}
func JudgementOfWisdomAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newDebuff(unit, judgementOfWisdomMeta, isPlayer, talentPoints)
}

// Curse of the Elements
var CurseOfElementsCategory = "CurseOfElements"
var curseOfElementsSpell = spelldata.MustFind(1311680)
var curseOfElementsMeta = &Meta{
	Label:      "Curse of the Elements",
	Spell:      curseOfElementsSpell,
	Category:   CurseOfElementsCategory,
	SingleAura: true,
}

func CurseOfElementsValue(talentPoints int32) float64 {
	return curseOfElementsMeta.Value(talentPoints)
}
func CurseOfElementsDuration(talentPoints int32) time.Duration {
	return curseOfElementsMeta.Duration(talentPoints)
}
func CurseOfElementsAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newDebuff(unit, curseOfElementsMeta, isPlayer, talentPoints)
}

// Curse of Recklessness
// Left out: effect 1 A_DUMMY(4) misc 0
// Left out: effect 3 A_PREVENTS_FLEEING(92) misc 0
var CurseOfRecklessnessCategory = "MinorArmorReduction"
var curseOfRecklessnessSpell = spelldata.MustFind(11717)
var curseOfRecklessnessMeta = &Meta{
	Label:    "Curse of Recklessness",
	Spell:    curseOfRecklessnessSpell,
	Category: CurseOfRecklessnessCategory,
	PerStat:  true,
}

func CurseOfRecklessnessValue(talentPoints int32) float64 {
	return curseOfRecklessnessMeta.Value(talentPoints)
}
func CurseOfRecklessnessDuration(talentPoints int32) time.Duration {
	return curseOfRecklessnessMeta.Duration(talentPoints)
}
func CurseOfRecklessnessAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newDebuff(unit, curseOfRecklessnessMeta, isPlayer, talentPoints)
}

// Faerie Fire
// Left out: effect 2 A_DISPEL_IMMUNITY(41) misc 6
// Left out: effect 3 A_DISPEL_IMMUNITY(41) misc 5
var FaerieFireCategory = "MinorArmorReduction"
var faerieFireSpell = spelldata.MustFind(9907)
var faerieFireMeta = &Meta{
	Label:    "Faerie Fire",
	Spell:    faerieFireSpell,
	Category: FaerieFireCategory,
	PerStat:  true,
}

func FaerieFireValue(talentPoints int32) float64 {
	return faerieFireMeta.Value(talentPoints)
}
func FaerieFireDuration(talentPoints int32) time.Duration {
	return faerieFireMeta.Duration(talentPoints)
}
func FaerieFireAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newDebuff(unit, faerieFireMeta, isPlayer, talentPoints)
}

// Expose Armor
var ExposeArmorCategory = "MajorArmorReduction"
var exposeArmorSpell = spelldata.MustFind(11198)
var exposeArmorMeta = &Meta{
	Label:           "Expose Armor",
	Spell:           exposeArmorSpell,
	Category:        ExposeArmorCategory,
	SingleAura:      true,
	FullComboPoints: true,
}

func ExposeArmorValue(talentPoints int32) float64 {
	return exposeArmorMeta.Value(talentPoints)
}
func ExposeArmorDuration(talentPoints int32) time.Duration {
	return exposeArmorMeta.Duration(talentPoints)
}
func ExposeArmorAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newDebuff(unit, exposeArmorMeta, isPlayer, talentPoints)
}

// Sunder Armor
var SunderArmorCategory = "MajorArmorReduction"
var sunderArmorSpell = spelldata.MustFind(11597)
var sunderArmorMeta = &Meta{
	Label:      "Sunder Armor",
	Spell:      sunderArmorSpell,
	Category:   SunderArmorCategory,
	SingleAura: true,
}

func SunderArmorValue(talentPoints int32) float64 {
	return sunderArmorMeta.Value(talentPoints)
}
func SunderArmorDuration(talentPoints int32) time.Duration {
	return sunderArmorMeta.Duration(talentPoints)
}
func SunderArmorAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newDebuff(unit, sunderArmorMeta, isPlayer, talentPoints)
}

// Gift of Arthas
var GiftOfArthasCategory = "GiftOfArthasAura"
var giftOfArthasSpell = spelldata.MustFind(11374)
var giftOfArthasMeta = &Meta{
	Label:      "Gift of Arthas",
	Spell:      giftOfArthasSpell,
	Category:   GiftOfArthasCategory,
	SingleAura: true,
}

func GiftOfArthasValue(talentPoints int32) float64 {
	return giftOfArthasMeta.Value(talentPoints)
}
func GiftOfArthasDuration(talentPoints int32) time.Duration {
	return giftOfArthasMeta.Duration(talentPoints)
}
func GiftOfArthasAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newDebuff(unit, giftOfArthasMeta, isPlayer, talentPoints)
}

// Demoralizing Roar
var DemoralizingRoarCategory = "Demoralizing"
var demoralizingRoarSpell = spelldata.MustFind(9898)
var demoralizingRoarMeta = &Meta{
	Label:      "Demoralizing Roar",
	Spell:      demoralizingRoarSpell,
	Category:   DemoralizingRoarCategory,
	SingleAura: true,
}

func DemoralizingRoarValue(talentPoints int32) float64 {
	return demoralizingRoarMeta.Value(talentPoints)
}
func DemoralizingRoarDuration(talentPoints int32) time.Duration {
	return demoralizingRoarMeta.Duration(talentPoints)
}
func DemoralizingRoarAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newDebuff(unit, demoralizingRoarMeta, isPlayer, talentPoints)
}

// Demoralizing Shout
var DemoralizingShoutCategory = "Demoralizing"
var demoralizingShoutSpell = spelldata.MustFind(11556)
var demoralizingShoutMeta = &Meta{
	Label:      "Demoralizing Shout",
	Spell:      demoralizingShoutSpell,
	Category:   DemoralizingShoutCategory,
	SingleAura: true,
}

func DemoralizingShoutValue(talentPoints int32) float64 {
	return demoralizingShoutMeta.Value(talentPoints)
}
func DemoralizingShoutDuration(talentPoints int32) time.Duration {
	return demoralizingShoutMeta.Duration(talentPoints)
}
func DemoralizingShoutAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newDebuff(unit, demoralizingShoutMeta, isPlayer, talentPoints)
}

// Thunder Clap
var ThunderClapCategory = "AtkSpdReduction"
var thunderClapSpell = spelldata.MustFind(11581)
var thunderClapMeta = &Meta{
	Label:    "Thunder Clap",
	Spell:    thunderClapSpell,
	Category: ThunderClapCategory,
}

func ThunderClapValue(talentPoints int32) float64 {
	return thunderClapMeta.Value(talentPoints)
}
func ThunderClapDuration(talentPoints int32) time.Duration {
	return thunderClapMeta.Duration(talentPoints)
}
func ThunderClapAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newDebuff(unit, thunderClapMeta, isPlayer, talentPoints)
}

// Insect Swarm
// Left out: effect 1 A_PERIODIC_DAMAGE(3) misc 0
var insectSwarmSpell = spelldata.MustFind(24977)
var insectSwarmMeta = &Meta{
	Label: "Insect Swarm",
	Spell: insectSwarmSpell,
}

func InsectSwarmValue(talentPoints int32) float64 {
	return insectSwarmMeta.Value(talentPoints)
}
func InsectSwarmDuration(talentPoints int32) time.Duration {
	return insectSwarmMeta.Duration(talentPoints)
}
func InsectSwarmAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newDebuff(unit, insectSwarmMeta, isPlayer, talentPoints)
}

// Scorpid Sting
var scorpidStingSpell = spelldata.MustFind(3043)
var scorpidStingMeta = &Meta{
	Label: "Scorpid Sting",
	Spell: scorpidStingSpell,
}

func ScorpidStingValue(talentPoints int32) float64 {
	return scorpidStingMeta.Value(talentPoints)
}
func ScorpidStingDuration(talentPoints int32) time.Duration {
	return scorpidStingMeta.Duration(talentPoints)
}
func ScorpidStingAura(unit *core.Unit, isPlayer bool, talentPoints int32) *core.Aura {
	return newDebuff(unit, scorpidStingMeta, isPlayer, talentPoints)
}

func applyGeneratedDebuffs(target *core.Unit, debuffs *proto.Debuffs, raid *proto.Raid) {
	if debuffs.HuntersMark {
		core.MakePermanent(HuntersMarkAura(target, false, 0))
	}
	if debuffs.JudgementOfLight {
		driveJudgementOfLight(target, debuffs, raid)
	}
	if debuffs.JudgementOfWisdom {
		driveJudgementOfWisdom(target, debuffs, raid)
	}
	if debuffs.CurseOfElements {
		core.MakePermanent(CurseOfElementsAura(target, false, 0))
	}
	if debuffs.CurseOfRecklessness {
		core.MakePermanent(CurseOfRecklessnessAura(target, false, 0))
	}
	if debuffs.FaerieFire {
		core.MakePermanent(FaerieFireAura(target, false, 0))
	}
	if debuffs.ExposeArmor {
		core.MakePermanent(ExposeArmorAura(target, false, 0))
	}
	if debuffs.SunderArmor {
		driveSunderArmor(target, debuffs, raid)
	}
	if debuffs.GiftOfArthas {
		core.MakePermanent(GiftOfArthasAura(target, false, 0))
	}
	if debuffs.DemoralizingRoar {
		core.MakePermanent(DemoralizingRoarAura(target, false, 0))
	}
	if debuffs.DemoralizingShout {
		core.MakePermanent(DemoralizingShoutAura(target, false, 0))
	}
	if debuffs.ThunderClap {
		core.MakePermanent(ThunderClapAura(target, false, 0))
	}
	if debuffs.InsectSwarm {
		core.MakePermanent(InsectSwarmAura(target, false, 0))
	}
	if debuffs.ScorpidSting {
		core.MakePermanent(ScorpidStingAura(target, false, 0))
	}
}
