// Code generated by tools/database/gen_spelldata. DO NOT EDIT.

package warrior

import (
	"github.com/wowsims/forever/sim/core/spelldata"
)

// Generated with an effect held at its base points, the talent tree stating no rank value for it:
//   Blood Craze: effect 1 of spell 16487 has no rank curve and is held at its base points
//   Gore Drinker: effect 0 of spell 1323967 has no rank curve and is held at its base points
//   Improved Slam: effect 2, 3, 4, 5, 6, 7 of spell 12862 has no rank curve and is held at its base points
//   Iron Will: effect 1 of spell 12962 has no rank curve and is held at its base points
//   Raging Blows: effect 0, 1 of spell 1310315 has no rank curve and is held at its base points
//   Vanguard: effect 0, 1, 2 of spell 1310317 has no rank curve and is held at its base points

type generatedSpellData struct {
	AngerManagement                 spelldata.Ladder
	Anticipation                    spelldata.Ladder
	Bastion                         spelldata.Ladder
	BattleShout                     spelldata.Ladder
	BattleStance                    spelldata.Ladder
	BattleStancePassive             spelldata.Ladder
	BerserkerRage                   spelldata.Ladder
	BerserkerStance                 spelldata.Ladder
	BerserkerStanceTriggered        spelldata.Ladder
	BerserkerStancePassive          spelldata.Ladder
	BloodCraze                      spelldata.Ladder
	BloodCrazeTriggered             spelldata.Ladder
	Bloodrage                       spelldata.Ladder
	BloodrageTriggered              spelldata.Ladder
	Bloodthirst                     spelldata.Ladder
	Bloodthrill                     spelldata.Ladder
	BloodthrillTriggered            spelldata.Ladder
	BoomingVoice                    spelldata.Ladder
	ChallengingShout                spelldata.Ladder
	Charge                          spelldata.Ladder
	ChargeTriggered                 spelldata.Ladder
	ChargeRageBonusEffect           spelldata.Ladder
	Cleave                          spelldata.Ladder
	ConcussionBlow                  spelldata.Ladder
	Cruelty                         spelldata.Ladder
	DeathWish                       spelldata.Ladder
	DeepWounds                      spelldata.Ladder
	DeepWoundsTriggered             spelldata.Ladder
	DefensiveStance                 spelldata.Ladder
	DefensiveStanceTriggered        spelldata.Ladder
	DefensiveStancePassive          spelldata.Ladder
	DefensiveStancePassiveTriggered spelldata.Ladder
	DefensiveState                  spelldata.Ladder
	DefensiveStateTriggered         spelldata.Ladder
	Defiance                        spelldata.Ladder
	Deflection                      spelldata.Ladder
	DemoralizingShout               spelldata.Ladder
	Disarm                          spelldata.Ladder
	DualWieldSpecialization         spelldata.Ladder
	Enrage                          spelldata.Ladder
	EnrageTriggered                 spelldata.Ladder
	Execute                         spelldata.Ladder
	ExecuteTriggered                spelldata.Ladder
	Flurry                          spelldata.Ladder
	FlurryTriggered                 spelldata.Ladder
	FocusedRage                     spelldata.Ladder
	FuriousPrecision                spelldata.Ladder
	GoreDrinker                     spelldata.Ladder
	Hamstring                       spelldata.Ladder
	HeroicStrike                    spelldata.Ladder
	Impale                          spelldata.Ladder
	ImprovedBattleShout             spelldata.Ladder
	ImprovedBerserkerRage           spelldata.Ladder
	ImprovedBloodrage               spelldata.Ladder
	ImprovedChallengingShout        spelldata.Ladder
	ImprovedCharge                  spelldata.Ladder
	ImprovedDemoralizingShout       spelldata.Ladder
	ImprovedDisarm                  spelldata.Ladder
	ImprovedExecute                 spelldata.Ladder
	ImprovedHamstring               spelldata.Ladder
	ImprovedHamstringTriggered      spelldata.Ladder
	ImprovedHeroicStrike            spelldata.Ladder
	ImprovedIntercept               spelldata.Ladder
	ImprovedIntimidatingShout       spelldata.Ladder
	ImprovedOverpower               spelldata.Ladder
	ImprovedPummel                  spelldata.Ladder
	ImprovedPummelTriggered         spelldata.Ladder
	ImprovedRend                    spelldata.Ladder
	ImprovedRevenge                 spelldata.Ladder
	ImprovedShieldBash              spelldata.Ladder
	ImprovedShieldBashTriggered     spelldata.Ladder
	ImprovedShieldBlock             spelldata.Ladder
	ImprovedShieldWall              spelldata.Ladder
	ImprovedSlam                    spelldata.Ladder
	ImprovedSunderArmor             spelldata.Ladder
	ImprovedTacticalMastery         spelldata.Ladder
	ImprovedTaunt                   spelldata.Ladder
	ImprovedThunderClap             spelldata.Ladder
	Intercept                       spelldata.Ladder
	InterceptTriggered              spelldata.Ladder
	IntimidatingShout               spelldata.Ladder
	IntimidatingShoutTriggered      spelldata.Ladder
	IronWill                        spelldata.Ladder
	LastStand                       spelldata.Ladder
	LastStandTriggered              spelldata.Ladder
	LingeringRage                   spelldata.Ladder
	LingeringRageTriggered          spelldata.Ladder
	LongDaze                        spelldata.Ladder
	MasterOfDefense                 spelldata.Ladder
	MasterOfDefenseTriggered        spelldata.Ladder
	MockingBlow                     spelldata.Ladder
	MortalStrike                    spelldata.Ladder
	OffensiveState                  spelldata.Ladder
	OffensiveStateTriggered         spelldata.Ladder
	Overpower                       spelldata.Ladder
	PiercingHowl                    spelldata.Ladder
	Pummel                          spelldata.Ladder
	RagingBlows                     spelldata.Ladder
	Recklessness                    spelldata.Ladder
	Rend                            spelldata.Ladder
	Retaliation                     spelldata.Ladder
	RetaliationTriggered            spelldata.Ladder
	Revenge                         spelldata.Ladder
	ShieldBash                      spelldata.Ladder
	ShieldBlock                     spelldata.Ladder
	ShieldSlam                      spelldata.Ladder
	ShieldSpecialization            spelldata.Ladder
	ShieldSpecializationTriggered   spelldata.Ladder
	ShieldWall                      spelldata.Ladder
	Slam                            spelldata.Ladder
	SpearingStrike                  spelldata.Ladder
	SunderArmor                     spelldata.Ladder
	SweepingStrikes                 spelldata.Ladder
	TacticalMastery                 spelldata.Ladder
	TacticalMasteryTriggered        spelldata.Ladder
	Taunt                           spelldata.Ladder
	ThunderClap                     spelldata.Ladder
	TwoHandedWeaponSpecialization   spelldata.Ladder
	UnbridledWrath                  spelldata.Ladder
	UnbridledWrathTriggered         spelldata.Ladder
	Vanguard                        spelldata.Ladder
	VictoriousState                 spelldata.Ladder
	VictoriousStateTriggered        spelldata.Ladder
	VictoryRush                     spelldata.Ladder
	VictoryRushTriggered            spelldata.Ladder
	Weaponmaster                    spelldata.Ladder
	Whirlwind                       spelldata.Ladder
}

var spellData = generatedSpellData{
	AngerManagement:                 spelldata.Ranked(12296),
	Anticipation:                    spelldata.Talent(12297, 5),
	Bastion:                         spelldata.Talent(16538, 5),
	BattleShout:                     spelldata.Ranked(6673, 5242, 6192, 11549, 11550, 11551, 25289),
	BattleStance:                    spelldata.Ranked(2457),
	BattleStancePassive:             spelldata.Ranked(21156),
	BerserkerRage:                   spelldata.Ranked(18499),
	BerserkerStance:                 spelldata.Ranked(2458),
	BerserkerStanceTriggered:        spelldata.Ranked(7381),
	BerserkerStancePassive:          spelldata.Ranked(7381),
	BloodCraze:                      spelldata.Talent(16487, 3),
	BloodCrazeTriggered:             spelldata.Ranked(16488),
	Bloodrage:                       spelldata.Ranked(2687),
	BloodrageTriggered:              spelldata.Ranked(29131),
	Bloodthirst:                     spelldata.Ranked(23881, 23892, 23893, 23894),
	Bloodthrill:                     spelldata.Talent(1289682, 5),
	BloodthrillTriggered:            spelldata.Ranked(1282733, 1289681),
	BoomingVoice:                    spelldata.Talent(12321, 5),
	ChallengingShout:                spelldata.Ranked(1161),
	Charge:                          spelldata.Ranked(100, 6178, 11578),
	ChargeTriggered:                 spelldata.Ranked(7922),
	ChargeRageBonusEffect:           spelldata.Ranked(12695, 12696),
	Cleave:                          spelldata.Ranked(845, 7369, 11608, 11609, 20569),
	ConcussionBlow:                  spelldata.Ranked(12809),
	Cruelty:                         spelldata.Talent(12320, 5),
	DeathWish:                       spelldata.Ranked(12328),
	DeepWounds:                      spelldata.Talent(12834, 3),
	DeepWoundsTriggered:             spelldata.Ranked(12162, 412609),
	DefensiveStance:                 spelldata.Ranked(71),
	DefensiveStanceTriggered:        spelldata.Ranked(7376, 12792),
	DefensiveStancePassive:          spelldata.Ranked(7376),
	DefensiveStancePassiveTriggered: spelldata.Ranked(12792),
	DefensiveState:                  spelldata.Ranked(5301),
	DefensiveStateTriggered:         spelldata.Ranked(5302),
	Defiance:                        spelldata.Talent(12792, 3),
	Deflection:                      spelldata.Talent(16462, 5),
	DemoralizingShout:               spelldata.Ranked(1160, 6190, 11554, 11555, 11556),
	Disarm:                          spelldata.Ranked(676),
	DualWieldSpecialization:         spelldata.Talent(23584, 5),
	Enrage:                          spelldata.Talent(12317, 5),
	EnrageTriggered:                 spelldata.Ranked(12880),
	Execute:                         spelldata.Ranked(5308, 20658, 20660, 20661, 20662),
	ExecuteTriggered:                spelldata.Ranked(26651),
	Flurry:                          spelldata.Talent(12319, 5),
	FlurryTriggered:                 spelldata.Ranked(12966),
	FocusedRage:                     spelldata.Talent(29787, 3),
	FuriousPrecision:                spelldata.Talent(1323963, 3),
	GoreDrinker:                     spelldata.Talent(1323967, 2),
	Hamstring:                       spelldata.Ranked(1715, 7372, 7373),
	HeroicStrike:                    spelldata.Ranked(78, 284, 285, 1608, 11564, 11565, 11566, 11567, 25286),
	Impale:                          spelldata.Talent(16493, 2),
	ImprovedBattleShout:             spelldata.Ranked(12318, 12857, 12858, 12860, 12861),
	ImprovedBerserkerRage:           spelldata.Talent(20500, 2),
	ImprovedBloodrage:               spelldata.Talent(12301, 2),
	ImprovedChallengingShout:        spelldata.Ranked(12327, 12886),
	ImprovedCharge:                  spelldata.Talent(12285, 2),
	ImprovedDemoralizingShout:       spelldata.Ranked(12324, 12876, 12877, 12878, 12879),
	ImprovedDisarm:                  spelldata.Talent(12313, 3),
	ImprovedExecute:                 spelldata.Talent(20502, 2),
	ImprovedHamstring:               spelldata.Talent(12289, 3),
	ImprovedHamstringTriggered:      spelldata.Ranked(23694),
	ImprovedHeroicStrike:            spelldata.Talent(12282, 3),
	ImprovedIntercept:               spelldata.Talent(20504, 2),
	ImprovedIntimidatingShout:       spelldata.Ranked(19870, 19871),
	ImprovedOverpower:               spelldata.Ranked(12290, 12963),
	ImprovedPummel:                  spelldata.Ranked(12288, 12707, 12708),
	ImprovedPummelTriggered:         spelldata.Ranked(12705),
	ImprovedRend:                    spelldata.Talent(12286, 3),
	ImprovedRevenge:                 spelldata.Talent(12797, 3),
	ImprovedShieldBash:              spelldata.Talent(12311, 2),
	ImprovedShieldBashTriggered:     spelldata.Ranked(18498),
	ImprovedShieldBlock:             spelldata.Ranked(12945, 12307, 12944),
	ImprovedShieldWall:              spelldata.Talent(12312, 2),
	ImprovedSlam:                    spelldata.Talent(12862, 2),
	ImprovedSunderArmor:             spelldata.Talent(12308, 3),
	ImprovedTacticalMastery:         spelldata.Talent(12295, 5),
	ImprovedTaunt:                   spelldata.Ranked(12302, 12765),
	ImprovedThunderClap:             spelldata.Talent(12287, 3),
	Intercept:                       spelldata.Ranked(20252, 20616, 20617),
	InterceptTriggered:              spelldata.Ranked(20253, 20614, 20615),
	IntimidatingShout:               spelldata.Ranked(5246),
	IntimidatingShoutTriggered:      spelldata.Ranked(20511),
	IronWill:                        spelldata.Talent(12962, 5),
	LastStand:                       spelldata.Ranked(12975),
	LastStandTriggered:              spelldata.Ranked(12976),
	LingeringRage:                   spelldata.Talent(1323964, 5),
	LingeringRageTriggered:          spelldata.Ranked(1323966),
	LongDaze:                        spelldata.Ranked(12705),
	MasterOfDefense:                 spelldata.Talent(1310316, 2),
	MasterOfDefenseTriggered:        spelldata.Ranked(23602),
	MockingBlow:                     spelldata.Ranked(694, 7400, 7402, 20559, 20560),
	MortalStrike:                    spelldata.Ranked(12294, 21551, 21552, 21553),
	OffensiveState:                  spelldata.Ranked(1282735),
	OffensiveStateTriggered:         spelldata.Ranked(1282733),
	Overpower:                       spelldata.Ranked(7384, 7887, 11584, 11585),
	PiercingHowl:                    spelldata.Ranked(12323),
	Pummel:                          spelldata.Ranked(6552, 6554),
	RagingBlows:                     spelldata.Talent(1310315, 1),
	Recklessness:                    spelldata.Ranked(1719),
	Rend:                            spelldata.Ranked(772, 6546, 6547, 6548, 11572, 11573, 11574),
	Retaliation:                     spelldata.Ranked(20230),
	RetaliationTriggered:            spelldata.Ranked(20240),
	Revenge:                         spelldata.Ranked(6572, 6574, 7379, 11600, 11601, 25288),
	ShieldBash:                      spelldata.Ranked(72, 1671, 1672),
	ShieldBlock:                     spelldata.Ranked(2565),
	ShieldSlam:                      spelldata.Ranked(23922, 23923, 23924, 23925),
	ShieldSpecialization:            spelldata.Talent(12298, 5),
	ShieldSpecializationTriggered:   spelldata.Ranked(1310318),
	ShieldWall:                      spelldata.Ranked(871),
	Slam:                            spelldata.Ranked(1240193, 1464, 8820, 11604, 11605),
	SpearingStrike:                  spelldata.Ranked(1310222),
	SunderArmor:                     spelldata.Ranked(7386, 7405, 8380, 11596, 11597),
	SweepingStrikes:                 spelldata.Ranked(12292),
	TacticalMastery:                 spelldata.Ranked(1310185),
	TacticalMasteryTriggered:        spelldata.Ranked(12295),
	Taunt:                           spelldata.Ranked(355),
	ThunderClap:                     spelldata.Ranked(6343, 8198, 8204, 8205, 11580, 11581),
	TwoHandedWeaponSpecialization:   spelldata.Talent(12163, 3),
	UnbridledWrath:                  spelldata.Talent(12322, 5),
	UnbridledWrathTriggered:         spelldata.Ranked(12964),
	Vanguard:                        spelldata.Talent(1310317, 1),
	VictoriousState:                 spelldata.Ranked(402974),
	VictoriousStateTriggered:        spelldata.Ranked(402975),
	VictoryRush:                     spelldata.Ranked(402927),
	VictoryRushTriggered:            spelldata.Ranked(402975),
	Weaponmaster:                    spelldata.Talent(1290261, 5),
	Whirlwind:                       spelldata.Ranked(1680),
}
