syntax = "proto3";
package proto;

option go_package = "./proto";

import "common.proto";
// DO NOT REMOVE THE COMMENTS
// BEGIN GENERATED
// DruidTalents message.
message DruidTalents {
    // Balance
    int32 improved_wrath = 1;
    int32 genesis = 2;
    int32 moonglow = 3;
    int32 improved_moonfire = 4;
    int32 natures_majesty = 5;
    int32 natures_reach = 6;
    int32 improved_entangling_roots = 7;
    bool natures_splendor = 8;
    bool insect_swarm = 9;
    int32 vengeance = 10;
    int32 improved_starfire = 11;
    int32 overgrowth = 12;
    bool natures_grace = 13;
    int32 eclipse = 14;
    int32 moonfury = 15;
    bool moonkin_form = 16;
    // Feral Combat
    int32 ferocity = 17;
    int32 heart_of_the_wild = 18;
    int32 feral_swiftness = 19;
    int32 feral_instinct = 20;
    int32 brutal_impact = 21;
    int32 thick_hide = 22;
    int32 shredding_attacks = 23;
    int32 savage_fury = 24;
    bool feral_charge = 25;
    int32 sharpened_claws = 26;
    bool shifting_power = 27;
    bool primal_bite = 28;
    int32 predatory_strikes = 29;
    int32 blood_frenzy = 30;
    int32 improved_shifting_power = 31;
    bool leader_of_the_pack = 32;
    int32 natural_instinct = 33;
    int32 natural_reaction = 34;
    int32 rend_and_tear = 35;
    bool berserk = 36;
    // Restoration
    int32 natures_focus = 37;
    int32 furor = 38;
    int32 naturalist = 39;
    int32 subtlety = 40;
    int32 natural_shapeshifter = 41;
    int32 reflection = 42;
    int32 gift_of_nature = 43;
    bool gift_of_the_earthmother = 44;
    int32 tranquil_spirit = 45;
    int32 improved_rejuvenation = 46;
    bool swiftmend = 47;
    bool natures_swiftness = 48;
    int32 living_spirit = 49;
    int32 improved_tranquility = 50;
    int32 improved_regrowth = 51;
    bool wild_growth = 52;
}

// END GENERATED

message DruidOptions {
	UnitReference innervate_target = 1;
}

message BalanceDruid {
  message Rotation {}

  message Options {
    DruidOptions class_options = 1;
	float okf_uptime = 2;
  }
  Options options = 3;
}

message FeralCatDruid {
  message Rotation {
    enum FinishingMove {
      Rip = 0;
      Bite = 1;
      None = 2;
    }

    FinishingMove finishing_move = 2;
    bool biteweave = 3;
    bool ripweave = 4;
    int32 rip_min_combo_points = 5;
    int32 bite_min_combo_points = 6;
    bool mangle_trick = 7;
    bool rake_trick = 8;
    bool maintain_faerie_fire = 9;
  }
  Rotation rotation = 1;

  message Options {
    DruidOptions class_options = 1;
    bool cannot_shred_target = 2;
  }
  Options options = 3;
}

message FeralBearDruid {
  message Rotation {
    bool maintain_faerie_fire = 1;
    bool maintain_demoralizing_roar = 2;
    int32 maul_rage_threshold = 3;

    enum SwipeUsage {
      SwipeUsage_Never = 0;
      SwipeUsage_WithEnoughAP = 1;
      SwipeUsage_Spam = 2;
    }
    SwipeUsage swipe_usage = 4;
    int32 swipe_ap_threshold = 5;
  }

  message Options {
    DruidOptions class_options = 1;
    double starting_rage = 2;
  }
  Options options = 3;
}

message RestorationDruid {
  message Rotation {}

  message Options {
    DruidOptions class_options = 1;
  }
  Options options = 3;
}
