// Code generated by tools/database/gen_spelldata. DO NOT EDIT.

package druid

import (
	"github.com/wowsims/forever/sim/core/spelldata"
)

// Not generated:
//   Improved Shred: missing rank 1 of 2

// Generated with an effect held at its base points, the talent tree stating no rank value for it:
//   Eclipse: effect 2, 3 of spell 408248 has no rank curve and is held at its base points
//   Gift of the Earthmother: effect 0 of spell 414673 has no rank curve and is held at its base points
//   Natural Reaction: effect 2, 3 of spell 417051 has no rank curve and is held at its base points
//   Nature's Splendor: effect 0, 1, 2 of spell 1223083 has no rank curve and is held at its base points
//   Predatory Strikes: effect 1 of spell 16972 has no rank curve and is held at its base points

type generatedSpellData struct {
	AbolishPoison             spelldata.Ladder
	AbolishPoisonTriggered    spelldata.Ladder
	AbolishPoisonEffect       spelldata.Ladder
	AquaticForm               spelldata.Ladder
	AquaticFormTriggered      spelldata.Ladder
	Barkskin                  spelldata.Ladder
	Bash                      spelldata.Ladder
	BearForm                  spelldata.Ladder
	BearFormTriggered         spelldata.Ladder
	BloodFrenzy               spelldata.Ladder
	BloodFrenzyTriggered      spelldata.Ladder
	BrutalImpact              spelldata.Ladder
	CatForm                   spelldata.Ladder
	CatFormTriggered          spelldata.Ladder
	ChallengingRoar           spelldata.Ladder
	Claw                      spelldata.Ladder
	Cower                     spelldata.Ladder
	CurePoison                spelldata.Ladder
	Dash                      spelldata.Ladder
	DeeperWilds               spelldata.Ladder
	DemoralizingRoar          spelldata.Ladder
	DireBearForm              spelldata.Ladder
	DireBearFormTriggered     spelldata.Ladder
	Eclipse                   spelldata.Ladder
	EclipseTriggered          spelldata.Ladder
	Enrage                    spelldata.Ladder
	EntanglingRoots           spelldata.Ladder
	EntanglingRootsTriggered  spelldata.Ladder
	FaerieFire                spelldata.Ladder
	FeralAggression           spelldata.Ladder
	FeralCharge               spelldata.Ladder
	FeralChargeTriggered      spelldata.Ladder
	FeralInstinct             spelldata.Ladder
	FeralSwiftness            spelldata.Ladder
	FerociousBite             spelldata.Ladder
	Ferocity                  spelldata.Ladder
	FrenziedRegeneration      spelldata.Ladder
	Furor                     spelldata.Ladder
	FurorTriggered            spelldata.Ladder
	Genesis                   spelldata.Ladder
	GiftOfNature              spelldata.Ladder
	GiftOfTheEarthmother      spelldata.Ladder
	GiftOfTheWild             spelldata.Ladder
	Growl                     spelldata.Ladder
	HealingTouch              spelldata.Ladder
	HeartOfTheWild            spelldata.Ladder
	Hibernate                 spelldata.Ladder
	Hurricane                 spelldata.Ladder
	HurricaneTriggered        spelldata.Ladder
	ImprovedEnrage            spelldata.Ladder
	ImprovedEnrageTriggered   spelldata.Ladder
	ImprovedEntanglingRoots   spelldata.Ladder
	ImprovedMarkOfTheWild     spelldata.Ladder
	ImprovedMoonfire          spelldata.Ladder
	ImprovedRegrowth          spelldata.Ladder
	ImprovedRejuvenation      spelldata.Ladder
	ImprovedShiftingPower     spelldata.Ladder
	ImprovedStarfire          spelldata.Ladder
	ImprovedStarfireTriggered spelldata.Ladder
	ImprovedThorns            spelldata.Ladder
	ImprovedTranquility       spelldata.Ladder
	ImprovedWrath             spelldata.Ladder
	Innervate                 spelldata.Ladder
	InsectSwarm               spelldata.Ladder
	Lacerate                  spelldata.Ladder
	LeaderOfThePack           spelldata.Ladder
	LeaderOfThePackTriggered  spelldata.Ladder
	LivingSpirit              spelldata.Ladder
	MarkOfTheWild             spelldata.Ladder
	Maul                      spelldata.Ladder
	Moonfire                  spelldata.Ladder
	Moonfury                  spelldata.Ladder
	Moonglow                  spelldata.Ladder
	MoonkinForm               spelldata.Ladder
	MoonkinFormTriggered      spelldata.Ladder
	NaturalInstinct           spelldata.Ladder
	NaturalReaction           spelldata.Ladder
	NaturalReactionTriggered  spelldata.Ladder
	NaturalShapeshifter       spelldata.Ladder
	NaturalWeapons            spelldata.Ladder
	Naturalist                spelldata.Ladder
	NaturesFocus              spelldata.Ladder
	NaturesGrace              spelldata.Ladder
	NaturesGraceTriggered     spelldata.Ladder
	NaturesGrasp              spelldata.Ladder
	NaturesGraspTriggered     spelldata.Ladder
	NaturesMajesty            spelldata.Ladder
	NaturesReach              spelldata.Ladder
	NaturesSplendor           spelldata.Ladder
	NaturesSwiftness          spelldata.Ladder
	OmenOfClarity             spelldata.Ladder
	OmenOfClarityTriggered    spelldata.Ladder
	Overgrowth                spelldata.Ladder
	Pounce                    spelldata.Ladder
	PounceTriggered           spelldata.Ladder
	PounceBleed               spelldata.Ladder
	PredatoryStrikes          spelldata.Ladder
	PrimalBite                spelldata.Ladder
	Prowl                     spelldata.Ladder
	Rake                      spelldata.Ladder
	Ravage                    spelldata.Ladder
	Rebirth                   spelldata.Ladder
	Reflection                spelldata.Ladder
	Regrowth                  spelldata.Ladder
	Rejuvenation              spelldata.Ladder
	RemoveCurse               spelldata.Ladder
	RendAndTear               spelldata.Ladder
	Revive                    spelldata.Ladder
	Rip                       spelldata.Ladder
	SavageFury                spelldata.Ladder
	SharpenedClaws            spelldata.Ladder
	ShiftingPower             spelldata.Ladder
	Shred                     spelldata.Ladder
	ShreddingAttacks          spelldata.Ladder
	SootheAnimal              spelldata.Ladder
	Starfire                  spelldata.Ladder
	Subtlety                  spelldata.Ladder
	Swiftmend                 spelldata.Ladder
	Swipe                     spelldata.Ladder
	TeleportMoonglade         spelldata.Ladder
	ThickHide                 spelldata.Ladder
	Thorns                    spelldata.Ladder
	TrackHumanoids            spelldata.Ladder
	TranquilSpirit            spelldata.Ladder
	Tranquility               spelldata.Ladder
	TravelForm                spelldata.Ladder
	TravelFormTriggered       spelldata.Ladder
	Vengeance                 spelldata.Ladder
	WildGrowth                spelldata.Ladder
	Wrath                     spelldata.Ladder
}

var spellData = generatedSpellData{
	AbolishPoison:             spelldata.Ranked(2893),
	AbolishPoisonTriggered:    spelldata.Ranked(3137),
	AbolishPoisonEffect:       spelldata.Ranked(3137),
	AquaticForm:               spelldata.Ranked(1066),
	AquaticFormTriggered:      spelldata.Ranked(5421),
	Barkskin:                  spelldata.Ranked(22812),
	Bash:                      spelldata.Ranked(5211, 6798, 8983),
	BearForm:                  spelldata.Ranked(5487),
	BearFormTriggered:         spelldata.Ranked(1178),
	BloodFrenzy:               spelldata.Talent(16958, 2),
	BloodFrenzyTriggered:      spelldata.Ranked(16959),
	BrutalImpact:              spelldata.Talent(16940, 2),
	CatForm:                   spelldata.Ranked(768),
	CatFormTriggered:          spelldata.Ranked(3025),
	ChallengingRoar:           spelldata.Ranked(5209),
	Claw:                      spelldata.Ranked(1082, 3029, 5201, 9849, 9850),
	Cower:                     spelldata.Ranked(8998, 9000, 9892),
	CurePoison:                spelldata.Ranked(8946),
	Dash:                      spelldata.Ranked(1850, 9821),
	DeeperWilds:               spelldata.Ranked(436956),
	DemoralizingRoar:          spelldata.Ranked(99, 1735, 9490, 9747, 9898),
	DireBearForm:              spelldata.Ranked(9634),
	DireBearFormTriggered:     spelldata.Ranked(9635),
	Eclipse:                   spelldata.Talent(408248, 3),
	EclipseTriggered:          spelldata.Ranked(408255),
	Enrage:                    spelldata.Ranked(5229),
	EntanglingRoots:           spelldata.Ranked(339, 1062, 5195, 5196, 9852, 9853),
	EntanglingRootsTriggered:  spelldata.Ranked(17245),
	FaerieFire:                spelldata.Ranked(770, 778, 9749, 9907),
	FeralAggression:           spelldata.Ranked(16858, 16859, 16860, 16861, 16862),
	FeralCharge:               spelldata.Ranked(1238122),
	FeralChargeTriggered:      spelldata.Ranked(19675),
	FeralInstinct:             spelldata.Talent(16947, 3),
	FeralSwiftness:            spelldata.Talent(17002, 2),
	FerociousBite:             spelldata.Ranked(22568, 22827, 22828, 22829, 31018),
	Ferocity:                  spelldata.Talent(16934, 5),
	FrenziedRegeneration:      spelldata.Ranked(22842),
	Furor:                     spelldata.Talent(17056, 5),
	FurorTriggered:            spelldata.Ranked(17057),
	Genesis:                   spelldata.Talent(1223081, 5),
	GiftOfNature:              spelldata.Talent(17104, 5),
	GiftOfTheEarthmother:      spelldata.Talent(414673, 1),
	GiftOfTheWild:             spelldata.Ranked(21849, 21850),
	Growl:                     spelldata.Ranked(6795),
	HealingTouch:              spelldata.Ranked(5185, 5186, 5187, 5188, 5189, 6778, 8903, 9758, 9888, 9889, 25297),
	HeartOfTheWild:            spelldata.Talent(17003, 5),
	Hibernate:                 spelldata.Ranked(2637, 18657, 18658),
	Hurricane:                 spelldata.Ranked(16914, 17401, 17402),
	HurricaneTriggered:        spelldata.Ranked(1278965, 1278968, 1278759),
	ImprovedEnrage:            spelldata.Ranked(17079, 17082),
	ImprovedEnrageTriggered:   spelldata.Ranked(17080, 17081),
	ImprovedEntanglingRoots:   spelldata.Talent(16918, 3),
	ImprovedMarkOfTheWild:     spelldata.Ranked(17050, 17051, 17053, 17054, 17055),
	ImprovedMoonfire:          spelldata.Talent(16821, 2),
	ImprovedRegrowth:          spelldata.Talent(17074, 5),
	ImprovedRejuvenation:      spelldata.Talent(17111, 3),
	ImprovedShiftingPower:     spelldata.Talent(1322670, 2),
	ImprovedStarfire:          spelldata.Talent(16850, 5),
	ImprovedStarfireTriggered: spelldata.Ranked(16922),
	ImprovedThorns:            spelldata.Ranked(16836, 16839, 16840),
	ImprovedTranquility:       spelldata.Talent(17123, 2),
	ImprovedWrath:             spelldata.Talent(16814, 5),
	Innervate:                 spelldata.Ranked(29166),
	InsectSwarm:               spelldata.Ranked(5570, 24974, 24975, 24976, 24977),
	Lacerate:                  spelldata.Ranked(414644, 1235826, 1235827),
	LeaderOfThePack:           spelldata.Ranked(17007),
	LeaderOfThePackTriggered:  spelldata.Ranked(24932),
	LivingSpirit:              spelldata.Talent(1309631, 3),
	MarkOfTheWild:             spelldata.Ranked(1126, 5232, 6756, 5234, 8907, 9884, 9885),
	Maul:                      spelldata.Ranked(6807, 6808, 6809, 8972, 9745, 9880, 9881),
	Moonfire:                  spelldata.Ranked(8921, 8924, 8925, 8926, 8927, 8928, 8929, 9833, 9834, 9835),
	Moonfury:                  spelldata.Talent(16896, 5),
	Moonglow:                  spelldata.Talent(16845, 3),
	MoonkinForm:               spelldata.Ranked(24858),
	MoonkinFormTriggered:      spelldata.Ranked(24905, 24907),
	NaturalInstinct:           spelldata.Talent(1223242, 2),
	NaturalReaction:           spelldata.Talent(417051, 5),
	NaturalReactionTriggered:  spelldata.Ranked(417053),
	NaturalShapeshifter:       spelldata.Talent(16833, 3),
	NaturalWeapons:            spelldata.Ranked(16902, 16903, 16904, 16905, 16906),
	Naturalist:                spelldata.Talent(17069, 5),
	NaturesFocus:              spelldata.Talent(17063, 5),
	NaturesGrace:              spelldata.Ranked(16880),
	NaturesGraceTriggered:     spelldata.Ranked(16886),
	NaturesGrasp:              spelldata.Ranked(16689, 16810, 16811, 16812, 16813, 17329),
	NaturesGraspTriggered:     spelldata.Ranked(19975, 19974, 19973, 19972, 19971, 19970),
	NaturesMajesty:            spelldata.Talent(1223082, 2),
	NaturesReach:              spelldata.Talent(16819, 2),
	NaturesSplendor:           spelldata.Talent(1223083, 1),
	NaturesSwiftness:          spelldata.Ranked(17116),
	OmenOfClarity:             spelldata.Ranked(16864),
	OmenOfClarityTriggered:    spelldata.Ranked(16870),
	Overgrowth:                spelldata.Talent(17245, 2),
	Pounce:                    spelldata.Ranked(9005, 9823, 9827),
	PounceTriggered:           spelldata.Ranked(9007, 9824, 9826),
	PounceBleed:               spelldata.Ranked(9007, 9824, 9826),
	PredatoryStrikes:          spelldata.Talent(16972, 3),
	PrimalBite:                spelldata.Ranked(407995, 1238069, 1238070, 1238073),
	Prowl:                     spelldata.Ranked(5215, 6783, 9913),
	Rake:                      spelldata.Ranked(1822, 1823, 1824, 9904),
	Ravage:                    spelldata.Ranked(6785, 6787, 9866, 9867),
	Rebirth:                   spelldata.Ranked(20484, 20739, 20742, 20747, 20748),
	Reflection:                spelldata.Talent(17106, 3),
	Regrowth:                  spelldata.Ranked(8936, 8938, 8939, 8940, 8941, 9750, 9856, 9857, 9858),
	Rejuvenation:              spelldata.Ranked(774, 1058, 1430, 2090, 2091, 3627, 8910, 9839, 9840, 9841, 25299),
	RemoveCurse:               spelldata.Ranked(2782),
	RendAndTear:               spelldata.Talent(1223246, 5),
	Revive:                    spelldata.Ranked(437138, 1237948, 1237949, 1237950, 1237951),
	Rip:                       spelldata.Ranked(1079, 9492, 9493, 9752, 9894, 9896),
	SavageFury:                spelldata.Talent(16998, 2),
	SharpenedClaws:            spelldata.Talent(16942, 2),
	ShiftingPower:             spelldata.Ranked(1322605),
	Shred:                     spelldata.Ranked(5221, 6800, 8992, 9829, 9830),
	ShreddingAttacks:          spelldata.Talent(16966, 3),
	SootheAnimal:              spelldata.Ranked(2908, 8955, 9901),
	Starfire:                  spelldata.Ranked(2912, 8949, 8950, 8951, 9875, 9876, 25298),
	Subtlety:                  spelldata.Talent(17118, 3),
	Swiftmend:                 spelldata.Ranked(18562),
	Swipe:                     spelldata.Ranked(779, 780, 769, 9754, 9908),
	TeleportMoonglade:         spelldata.Ranked(18960),
	ThickHide:                 spelldata.Talent(16929, 3),
	Thorns:                    spelldata.Ranked(467, 782, 1075, 8914, 9756, 9910),
	TrackHumanoids:            spelldata.Ranked(5225),
	TranquilSpirit:            spelldata.Talent(24968, 5),
	Tranquility:               spelldata.Ranked(740, 8918, 9862, 9863),
	TravelForm:                spelldata.Ranked(783),
	TravelFormTriggered:       spelldata.Ranked(5419),
	Vengeance:                 spelldata.Talent(16909, 5),
	WildGrowth:                spelldata.Ranked(408120, 1238214, 1238215),
	Wrath:                     spelldata.Ranked(5176, 5177, 5178, 5179, 5180, 6780, 8905, 9912),
}
